### ISSUE TITLE
创建比赛失败

### ISSUE THREAD

**Issue by s094392** [QingdaoU/OnlineJudge#1]
使用管理员帐号创建比赛时一直失败
提示请求失败

**Comment by virusdefender** [comment]
F12打开控制台，看看有没有 js 出错啊

有的话，截图看看
![qq20151021-0](https://cloud.githubusercontent.com/assets/4939404/10633134/5cb3ad72-781b-11e5-9324-655c91b75c1a.png)

**Comment by virusdefender** [comment]
比赛功能这两天会修改，目前的问题还有点多。

**Comment by virusdefender** [comment]
抱歉，我知道怎么回事了，我这部分代码还没改完就发布了。后端出错了，我明晚之前尽量改过来。

**Comment by virusdefender** [comment]
fixed

**Comment by adamwen829** [comment]
:trophy:
