### ISSUE TITLE
请问怎么能重用Judger到我自己的项目里？我的项目也是涉及在线C/C++编译器。

### ISSUE THREAD

**Issue by tonygao2k** [QingdaoU/OnlineJudge#104]
在提交issue之前请

  - 认真阅读文档 https://github.com/QingdaoU/OnlineJudge/wiki
  - 搜索和查看历史issues
 
然后提交issue请写清楚下列事项
 
  - 进行什么操作的时候遇到了什么问题
  - 错误提示是什么，如果看不到错误提示，请去log文件夹查看。大段的错误提示请包在代码块标记里面。
  - 你尝试修复问题的操作
  - 页面问题请写清浏览器版本，尽量有截图

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/JudgeServer
