### ISSUE TITLE
希望增加一个上传网站icon的功能。

### ISSUE THREAD

**Issue by wxz7801** [QingdaoU/OnlineJudge#107]
希望增加一个上传网站icon的功能放在后台管理，只能由超级管理员操作，这样可以进一步方便自定义网站。

**Comment by zema1** [comment]
你指的是`favicon`吧，下次更新加上

**Comment by virusdefender** [comment]
加了，请 `docker-compose pull && docker-compose up -d` 试试

文件存放在 `data/backend/public/website/favicon.ico`
