### ISSUE TITLE
IE11下，题目详情界面中的样例输入、输出的内容没有在框里。

### ISSUE THREAD

**Issue by wxz7801** [QingdaoU/OnlineJudge#109]
![LnQZq.png](https://s1.ax1x.com/2017/12/15/LnQZq.png)
如图。
IE版本：11.125.16299.0

**Comment by zema1** [comment]
这是因为IE11对flex的支持很buggy，这里用到了`flex-direction: column;`来使input和output拥有相同的高度，这个属性IE11支持的很烂

**Comment by zema1** [comment]
请更新至新版 新版已解决
