### ISSUE TITLE
大量输出导致服务器近乎死机

### ISSUE THREAD

**Issue by Luffbee** [QingdaoU/OnlineJudge#116]
一个A+B的测试题目，之前为了测压，丢了300组数据。然后今天有人提交了一个while死循环里不停的printf的代码，导致服务器的内存用光，swap也用光，然后就服务没有响应了。下面是之后复现时htop的结果截图，可以看出主要是gunicorn在吃内存。虽然服务器配置不高，但这个问题还是算挺严重的吧。不知可否增加OLE之类的限制来防止这种问题。
![capture](https://user-images.githubusercontent.com/17215435/34415207-5a3c43e6-ec28-11e7-9263-a757e837a28c.PNG)

**Comment by virusdefender** [comment]
十分感谢，目前其实是有 OLE 的，但是默认没开限制，不过可以随时增加，因为存储了测试用例的大小。

内存用量这么大的原因应该是用户代码的 output 也是重定向到 tmpfs 中的，也就是内存，导致大量占用。

但是为什么显示 gunicorn 也有这么大的内存占用，需要等待我复现问题。

**Comment by virusdefender** [comment]
想了一下这个问题，感觉还得往后推一下。

**Comment by virusdefender** [comment]
修复了这个问题的其中一部分

https://github.com/QingdaoU/JudgeServer/commit/d579874094e94ac345db098b989fe4d18b3e6dd8

**Comment by virusdefender** [comment]
修复了这个问题的第二部分

https://github.com/QingdaoU/JudgeServer/commit/9e9728fce2c13126bc67361c1b449426653911a0
