### ISSUE TITLE
Armv7l环境运行错误

### ISSUE THREAD

**Issue by iamapig120** [QingdaoU/OnlineJudge#120]
设备 树莓派3b
系统 Raspbian 4.x

docker镜像
    postgres 正常
    redis 无限重启，log输出错误 缺失文件
    其余两个组件均无法运行 standrad_init_linux.go:195 报错 exec user process caused "exec format error"

**Comment by iamapig120** [comment]
redis 通过更改镜像已正常运行

**Comment by virusdefender** [comment]
因为镜像不是为arm环境构建的，肯定是不可以运行的，如果需要，可以尝试自己构建下镜像。
