### ISSUE TITLE
C++编译莫名其妙报错

### ISSUE THREAD

**Issue by liz0ng** [QingdaoU/OnlineJudge#122]
![image](https://user-images.githubusercontent.com/35164246/36353096-0d69c702-14fd-11e8-8e08-544a2ada95a5.png)

**Comment by liz0ng** [comment]
OJ地址：test.lizong.pw

**Comment by virusdefender** [comment]
链接无法访问，提示 `Sorry, the page you are looking for could not be found.`

麻烦检查下这个题目有没有 template
