### ISSUE TITLE
希望支持自定义编译器和语言，例如

### ISSUE THREAD

**Issue by ICEYSELF** [QingdaoU/OnlineJudge#125]
clang++-5.0 -std=c++14 -Wall -Werror
clang++-6.0 -std=c++17 -Wall -Werror -O2

**Comment by ILoveChenKX** [comment]
Issue #124 中提到的不支持Pascal的问题也可以通过手动增添配置的方式解决。

**Comment by virusdefender** [comment]
目前编译器的配置都是在 https://github.com/QingdaoU/OnlineJudge/blob/master/judge/languages.py 确定的

可以自己先构建对应的 judge-server 镜像，然后修改这个配置

需要思考下，这个配置怎么去提供编辑

**Comment by 1481767320** [comment]
#124 : 不会这些，可以请各位大佬帮一下吗？

**Comment by hysci** [comment]
Could CUDA compiler be supported by "nvidia-docker"?

**Comment by virusdefender** [comment]
@hysci  compiler is easy to be replaced, but there may be some issues with the binary (sandbox, hardware, etc)
