### ISSUE TITLE
Rejudge 後 ，Problem 的 Total 會重複計算

### ISSUE THREAD

**Issue by tico88612** [QingdaoU/OnlineJudge#126]
如果在 Status 按下 Rejudge 後
Problem 的 Submission Total 會重複計算（會累加上去）

**Comment by 1481767320** [comment]
同样
但应该不影响使用吧？

**Comment by tico88612** [comment]
不影響使用，但AC跟WA的比率會很奇怪就是了

**Comment by 1481767320** [comment]
是有点奇怪
图表按AC 与 WA 的用户数来画就没事了吧

**Comment by virusdefender** [comment]
稍后看下 @zema1

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/pull/130

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/pull/131
