### ISSUE TITLE
数据上传的问题

### ISSUE THREAD

**Issue by 1481767320** [QingdaoU/OnlineJudge#127]
从Mac OS拷来的数据，压缩成ZIP后上传，显示Empty File
自己做的数据压缩后上传是没有问题的
求如何解决

**Comment by virusdefender** [comment]
`unzip -v testcase.zip` 看看，最顶层就应该是 in out 文件，而不是其他的文件夹

**Comment by 1481767320** [comment]
发现不是没有放在ZIP根目录的问题，本来文件名是data1.in, data1.out这样的，改成1.in, 1.out就好了

**Comment by virusdefender** [comment]
嗯嗯，这个就是这么要求的。

**Comment by liuxuehao** [comment]
请问这个1.in和1.out里边写什么内容呀
