### ISSUE TITLE
C/C++和Python都可以使用，唯独Java总是RE或CE

### ISSUE THREAD

**Issue by ShiinaHikari** [QingdaoU/OnlineJudge#128]
已经尝试在Ubuntu中装openjdk1.7，无效
使用了最简单的A+B测试
样例数据:
In：1 2
Out：3

**Comment by virusdefender** [comment]
这个是已知问题，你需要先把内存限制加大。

**Comment by hygoni** [comment]
Sorry, I have same problem
How can I increase memory limit?
do you mean increasing memory of docker container?
by docker update --memory=XXXXXX judge-server?

**Comment by hygoni** [comment]
Not complete same problem. My Judge doesn't even say
the problem is CE or RE. 
it just stay "Submitting..."
