### ISSUE TITLE
在按照文档更新之后所有数据全部消失.

### ISSUE THREAD

**Issue by PatrickStarCat** [QingdaoU/OnlineJudge#133]
按照官方文档的执行语句更新OJ后 所有数据全部消失.

**Comment by virusdefender** [comment]
`docker inspect oj-backend | grep Mounts -C 10` 看下 `Source` 是当前目录么？

因为这个 source 的前缀是 `$PWD`，如果环境变量不存在可能造成问题。

比如第一次安装的时候，并非在 docker-compose.yml 所在的目录而是它的下级目录，这样 data 目录就存在于下级目录中。之后在其他的目录中重新 up -d 就会导致重新创建 data 目录。

**Comment by virusdefender** [comment]
没有回复，暂时关闭，有任何疑问可以补充回复。
