### ISSUE TITLE
如何import第三方包

### ISSUE THREAD

**Issue by kevinljw** [QingdaoU/OnlineJudge#135]
如题，若题目需使用如requests、beautifulsoup、pyquery等python第三方包，该如何正确安装？

**Comment by virusdefender** [comment]
这个是Python基础吧，没懂你是遇到了什么问题。有需要可以继续回复。

**Comment by kevinljw** [comment]
您可能误会我的意思，我指的是如果出与使用beautifulsoup这类第三方包有关的题目，但没有在此OJ上先安装应跑不起来。我想知道应该在哪裡跑像pip install beautifulsoup4指令，方能import解这类题。谢谢您

**Comment by virusdefender** [comment]
加到项目中的 requirements.txt 中

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/JudgeServer/blob/master/Dockerfile

需要写在 JudgeServer 的环境中

**Comment by kevinljw** [comment]
在不修改原本Dockerfile的情形下，则根据此行：
`pip3 install --no-cache-dir psutil gunicorn flask requests && \`
表示原本已预装requests。
若到OJ裡只送出import requests这行代码，会得到Runtime Error，很可能表示认不得此包。
也做过其他包尝试，仍是同样结果，可以有更详细说明如何正确安装吗？谢谢您

**Comment by virusdefender** [comment]
这是因为 JudgeServer 为了安全禁用了部分系统调用的原因吧

https://github.com/QingdaoU/OnlineJudge/blob/master/judge/languages.py#L145
https://github.com/QingdaoU/Judger/blob/newnew/src/rules/general.c

如果要放开这个限制就降低了安全性，这个和部分模块是冲突的，需要自己取舍一下。

**Comment by kevinljw** [comment]
已尝试去除execve、open、openat等KILL限制，仍没效，有什麽方法吗？需要改docker-compose内的cap_drop吗？
另文档`data/judge_server/log/judge.log`只有创建，一直没出现讯息，该如何得知每次judge跑出Runtime Time Error其内相关讯息？希望指教谢谢

**Comment by virusdefender** [comment]
给 judge server 设置这个环境变量，然后就不会自动删除用户输出了，然后去 /judge_run 下面看看

https://github.com/QingdaoU/JudgeServer/blob/master/server/server.py#L15

**Comment by kevinljw** [comment]
跑过后有看到代码(py)、pyc、输出(out)，但没有打印错误讯息，无从得知目前状况。有其他方法吗？再麻烦您了谢谢

**Comment by kevinljw** [comment]
out裡是print()所打印的内容，求解

**Comment by virusdefender** [comment]
贴一下你的代码，你修改了什么东西，还有提交详情页的截图，还有运行代码之后主机上运行下 `dmesg` 看看有没有拦截记录

**Comment by IsaacHumera** [comment]
@kevinljw 您好，我遇到了像您一样的需求，需要添加与使用`numpy,pandas`这些第三方包有关的题目，并与您一样遇到了相同的问题，请问您的问题解决了吗？谢谢您
