### ISSUE TITLE
JudgeServer  unable to attach to Backend Server 

### ISSUE THREAD

**Issue by lugt** [QingdaoU/OnlineJudge#137]
Thx for your time.

It has been days for me to toy out this OnlineJudge System, I have been keen to make some changes to the `seccomp` and `docker` integrations thus trying to build the whole system outside docker.

Up to this point, I had the server (backend 8000) and the front-end part running, and it looks fine.
All users and management and other functionalities working alongside.
(It's a fact that I haven't implemented any of the initializing script / installation script, rather, I have created the default users using postgres tools and changed their roles to `super admin` manually)

Yet the troubling part was the JudgerServer that should be (by default) running on a docker platform.
I was trying to run the JudgerServer using direct command line, without docker.

Here is the command-line I used.
```
ubuntu $   python3 gunicorn --time 600 --bind 0.0.0.0:8090 server:app

[2018-04-13 08:39:08 +0000] [6495] [INFO] Starting gunicorn 19.7.1
[2018-04-13 08:39:08 +0000] [6495] [INFO] Listening at: http://0.0.0.0:8090 (6495)
[2018-04-13 08:39:08 +0000] [6495] [INFO] Using worker: sync
[2018-04-13 08:39:08 +0000] [6499] [INFO] Booting worker with pid: 649
```
Yet this turned out to successfully creating the WebServer in gunicorn,
visible through `http://127.0.0.1:8090/ping`

And in browser I get
```
{"err": "TokenVerificationFailed", "data": "invalid token"}
```

Yet the infos on the page
```
http://localhost:8080/admin/judge-server

```
was displaying 
```
Status | Hostname | Task Number | CPU Core | CPU Usage | Memory Usage | Disabled |  
Abnormal | ubuntu | 0 | 2 | 69.8% | 61.6% | 
```

I have manually runned the `service.py` script sometimes to add this JudgeServer to the backend.
Yet the submissions remained unchecked, labeled `Pending`.

Do I lack some of the configuration procedure?

**Comment by lugt** [comment]
somehow I have used service.py to let the backend server aware of the JudgerServer, yet still the questions wasn't evaluated,

I used some client / Python / client.py to test over the server : 
```
{'data': {'judger_version': '2.1.1', 'hostname': 'ubuntu', 'cpu_core': 2, 'memory': 59.2, 'action': 'pong', 'cpu': 0.0}, 'err': None} 


compile_spj
http://127.0.0.1:8090/compile_spj
app reached,compile_spj
<Response [200]>
app reached,compile_spj
{'data': "TypeError :'encoding' is an invalid keyword argument for this function", 'err': 'JudgeClientError'} 


c_judge
http://127.0.0.1:8090/judge
app reached,judge
<Response [200]>
app reached,judge
{'data': 'TypeError :super() takes at least 1 argument (0 given)', 'err': 'JudgeClientError'} 


cpp_judge
http://127.0.0.1:8090/judge
app reached,judge
<Response [200]>
app reached,judge
{'data': 'TypeError :super() takes at least 1 argument (0 given)', 'err': 'JudgeClientError'} 


java_judge
http://127.0.0.1:8090/judge
app reached,judge
<Response [200]>
app reached,judge
{'data': 'TypeError :super() takes at least 1 argument (0 given)', 'err': 'JudgeClientError'} 


c_spj_judge
http://127.0.0.1:8090/judge
app reached,judge
<Response [200]>
app reached,judge
{'data': "TypeError :'encoding' is an invalid keyword argument for this function", 'err': 'JudgeClientError'} 


py2_judge
http://127.0.0.1:8090/judge
app reached,judge
<Response [200]>
app reached,judge
{'data': 'TypeError :super() takes at least 1 argument (0 given)', 'err': 'JudgeClientError'} 


py3_judge
http://127.0.0.1:8090/judge
app reached,judge
<Response [200]>
app reached,judge
{'data': 'TypeError :super() takes at least 1 argument (0 given)', 'err': 'JudgeClientError'} 


```

**Comment by lugt** [comment]
commented the 
```
... super().__init__() ...
```
line from ` server /  exception.py `

that `super takes at least 1 argument` error has dropped and new one comes, 

```
c_judge
http://127.0.0.1:8090/judge
{'data': 'ValueError :args item must be a string', 'err': 'JudgeClientError'} 
```

**Comment by lugt** [comment]
With some tweeks, it became

```
compile_spj
http://127.0.0.1:8090/compile_spj
<Response [200]>
{'err': None, 'data': 'success'} 


c_judge
http://127.0.0.1:8090/judge
<Response [200]>
{'err': 'JudgeClientError', 'data': 'Test case not found'} 


cpp_judge
http://127.0.0.1:8090/judge
<Response [200]>
{'err': 'JudgeClientError', 'data': 'Test case not found'} 
```

**Comment by zema1** [comment]
You may forget to run `celery`. A submission is regarded as an asynchronous task using celery to boost it. Try this line in the django root path.
```
celery -A oj worker -l warning
```
You can find the script here. [https://github.com/QingdaoU/OnlineJudge/blob/master/deploy/supervisord.conf](https://github.com/QingdaoU/OnlineJudge/blob/master/deploy/supervisord.conf)

Actually, the judge_server is supposed to run in container using `docker-compose`. We use docker-compose to drop some dangerous capabilities. In other words, it's a bit unsafe  to run the container directly.  Details: [https://github.com/QingdaoU/JudgeServer/blob/master/docker-compose.example.yml](https://github.com/QingdaoU/JudgeServer/blob/master/docker-compose.example.yml)

**Comment by lugt** [comment]
Later on, when anyone submitted anything, it showed the compiling error
```
Test case not found
```

detialling, it showed as if the INFO file was missing in the case

I was wondering if I should manually unzip the test cases into /test_case ?

**Comment by virusdefender** [comment]
/test_case/{test case id in the db}/1.{in,out}
