### ISSUE TITLE
fail to upload testcase

### ISSUE THREAD

**Issue by eagle705** [QingdaoU/OnlineJudge#138]
I'm trying to upload testcase through admin page by using Choose File.

when I upload testcase.zip (1.in, 1.out is in this file), "Empty file" error message appear.

How can I fix it?

**Comment by virusdefender** [comment]
You should lcoation *.{in,out} in the root level of the testcase zip file

`testcase.zip`is the wrong usage

![image](https://user-images.githubusercontent.com/4939404/38804524-44b6ce60-41a5-11e8-9136-fae9073568c5.png)

**Comment by keepchen** [comment]
> https://docs.onlinejudge.me/#/onlinejudge/guide/test_case
> 
> You should lcoate *.{in,out} in the root level of the test case zip file
> 
> `testcase.zip`is the wrong usage
> 
> ![image](https://user-images.githubusercontent.com/4939404/38804524-44b6ce60-41a5-11e8-9136-fae9073568c5.png)
> 
> If you still have some problems, be free to reply in this issue

Although it looks strange, it works!

```shell
% unzip -v ttt.zip
Archive:  ttt.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       2  Defl:N        4 100% 05-25-2020 17:12 55679ed1  1.out
     276  Defl:N      133  52% 05-25-2020 17:12 a94fc445  __MACOSX/._1.out
       4  Defl:N        6 -50% 05-25-2020 17:12 55214233  1.in
     276  Defl:N      133  52% 05-25-2020 17:12 b2b586ef  __MACOSX/._1.in
--------          -------  ---                            -------
     558              276  51%                            4 files
```

Thanks a lot!
