### ISSUE TITLE
I want to modify front-end source, how can I do that?

### ISSUE THREAD

**Issue by eagle705** [QingdaoU/OnlineJudge#140]
I think this online judge system is REALLY awesome:)

However I want to modify two parts.

1. I want to change code editor something like monaco.

2. I want to add result page when user run their source code.

I see there is 4 docker process (when I command docker ps -a)
"oj-backend, oj-redis, judge-server, oj-postgres"
which one is I have to modify? is there any guide?

**Comment by virusdefender** [comment]
maybe https://github.com/QingdaoU/OnlineJudge/issues/139 will help
