### ISSUE TITLE
被Root修改过的题目创建人会变成Root，且原创建人不能再编辑原题目

### ISSUE THREAD

**Issue by LyricSeraph** [QingdaoU/OnlineJudge#141]
如题。
我有个普通管理员A，创建了一个题目B。
这个题目一直都能被正常编辑，直到不小心用Root超级管理员进到编辑页面进行了修改并保存后，题目的created_by属性变成了root，并且普通管理员点击该题目的编辑按钮时会出现“Problem does not exist”的提示，编辑题目的表单不能正常加载。
接口problem?id=:id的请求结果为：
{
    "error": "error",
    "data": "Problem does not exist"
}
暂时没找到解决方法

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/commit/79724b04639bd0981dab4fda89a8e7fc2cf62887

感谢，稍后会合并其他的修复推送新版本
