### ISSUE TITLE
test_case info 的格式要求

### ISSUE THREAD

**Issue by GarrickLin** [QingdaoU/OnlineJudge#142]
在部署题目的时候，[info](https://docs.onlinejudge.me/#/judgeserver/testcase?id=normal-problem)文件不大知道该怎么填，例如
```
{
    "spj": false,
    "test_cases": {
        "1": {            
            "striped_output_md5": "eccbc87e4b5ce2fe28308fd9f2a7baf3",
            "output_size": 2,
            "input_name": "1.in",
            "input_size": 4,
            "output_name": "1.out"
        }
    }
}
```
上述模板中
- `striped_output_md5` 代表什么意思， 应该如何生成
- `output_size` `input_size` 分别表示什么意思

所以能不能解惑一下或者多提供几个 test_case 的样板来模仿一下？谢谢！

**Comment by crazyX-CN** [comment]
info文件不需要自己填吧，不是自动生成的么


Yours Sincerely,
Jingwei Xu

--
University of Science and Technology Beijing
Xueyuan Rd.30, Haidian Dist,Beijing,
China
100083


________________________________
发件人: XianyanLin <notifications@github.com>
发送时间: 2018年4月19日 23:02
收件人: QingdaoU/OnlineJudge
抄送: Subscribed
主题: [QingdaoU/OnlineJudge] test_case info 的格式要求 (#142)


在部署题目的时候，info<https://docs.onlinejudge.me/#/judgeserver/testcase?id=normal-problem>文件不大知道该怎么填，例如

{
    "spj": false,
    "test_cases": {
        "1": {
            "striped_output_md5": "eccbc87e4b5ce2fe28308fd9f2a7baf3",
            "output_size": 2,
            "input_name": "1.in",
            "input_size": 4,
            "output_name": "1.out"
        }
    }
}


上述模板中

  *   striped_output_md5 代表什么意思， 应该如何生成
  *   output_size input_size 分别表示什么意思

所以能不能解惑一下或者多提供几个 test_case 的样板来模仿一下？谢谢！

―

**Comment by virusdefender** [comment]
如果上网页上传测试用例，不需要手动生成 info
