### ISSUE TITLE
I'm trying to add C# compiler but it doesn't work..

### ISSUE THREAD

**Issue by eagle705** [QingdaoU/OnlineJudge#143]
HI, I'm now working on adding c# compiler (mono) to ```judge server```    
(http://www.mono-project.com/download/stable/#download-lin)

However, when I compile source code in C# mode, status is **pending**
```
Pending
Time: -- Memory: -- Lang: C# Author: eagle
```

Here is my configuration. (/app/judge/lanaguages.py in oj-backend)   
(I installed mono on judge server)

```python
_csharp_lang_config = {
    "template": """//PREPEND BEGIN
//PREPEND END

//TEMPLATE BEGIN
//TEMPLATE END

//APPEND BEGIN
//APPEND END""",
    "compile": {
        "src_name": "main.cs",
        "exe_name": "main",
        "max_cpu_time": 3000,
        "max_real_time": 5000,
        "max_memory": 256 * 1024 * 1024,
        "compile_command": "/usr/bin/dmcs {src_path} -out:{exe_path}",
    },
    "run": {
        "command": "/usr/bin/mono {exe_path}",
        "seccomp_rule": "c_sharp",
        "env": default_env
    }
}


languages = [
    {"config": _c_lang_config, "spj": {"compile": _c_lang_spj_compile, "config": _c_lang_spj_config},
     "name": "C", "description": "GCC 5.4", "content_type": "text/x-csrc"},
    {"config": _cpp_lang_config, "spj": {"compile": _cpp_lang_spj_compile, "config": _cpp_lang_spj_config},
     "name": "C++", "description": "G++ 5.4", "content_type": "text/x-c++src"},
    {"config": _java_lang_config, "name": "Java", "description": "OpenJDK 1.8", "content_type": "text/x-java"},
    {"config": _py2_lang_config, "name": "Python2", "description": "Python 2.7", "content_type": "text/x-python"},
    {"config": _py3_lang_config, "name": "Python3", "description": "Python 3.5", "content_type": "text/x-python"},
    {"config": _csharp_lang_config, "name": "C#", "description": "C#", "content_type": "text/x-csharp"}
]
```

How am I supposed to solve?  
+) Addtionally, What is SPJ?

**Comment by eagle705** [comment]
Now, I'm add SPJ option like c, and c++ then success compile. However, Syntax error occured..! (the cod is correct but syntax error occured..)
My second question is, what is "seccomp_rule"??

**Comment by virusdefender** [comment]
Sorry for the late response, may be it difficult to debug this issue under judge server environment, there are several suggestions

- if the runtime error's signal is 31, it means `mono` is killed by seccomp, then please refer the second suggestion
 - you can set `seccomp_rule=None` to disable security limitations and remember to run `cd /app/deploy && supervisorctl restart celery`

if `mono` is killed by seccomp, it means it calls some forbidden system calls, run `dmesg` can get some audit logs, please reply this issue with the logs

 - set `judger_debug=1` env in `docker-compose.yml` judge-server section, after submitting a solution, `docker exec -it judge-server /bin/bash` and then `cd /judger_run`, you can get the compiled binary and its stdout / stderr output, it may help
 - use judger python binding to run mono to debug https://docs.onlinejudge.me/#/judger/api?id=python-demo
