### ISSUE TITLE
判题服务器的bug

### ISSUE THREAD

**Issue by hirCodd** [QingdaoU/OnlineJudge#145]
判题服务器在处于disable的状态时，用户进行problem submission，当切换判题服务器为可用时，状态依然是pending，只有重新再提交一次才能重新进行判题(包括之前的pending)。

**Comment by virusdefender** [comment]
嗯，确认问题存在。

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/commit/8ee1b514e372dc14e85e5d3f26b32197a9d4c366
