### ISSUE TITLE
OJ无法更新

### ISSUE THREAD

**Issue by 1481767320** [QingdaoU/OnlineJudge#146]
更新OJ时，总是会提示ERROR: manifest for registry.docker-cn.com/library/redis:4.0-alpine not found，后来发现是这个网站没有备案所导致，现在无法更新，请求帮助

**Comment by virusdefender** [comment]
网站确实一直提示没有备案，不过和这个没关系，我这里测试可用。

如果是更新镜像，`docker-compose pull oj-backend judge-server` 就够了，如果是全新安装，你可以把`registry.docker-cn.com/library/` 前缀去掉。
