### ISSUE TITLE
服务器重启后Root用户登陆失败

### ISSUE THREAD

**Issue by sdtalyk** [QingdaoU/OnlineJudge#147]
重启服务器后使用Root用户登陆会失败。
提示：server error。
而其他用户登陆没有问题。

我是严格按照[安装文档](https://github.com/QingdaoU/OnlineJudgeDeploy/tree/2.0)的说明在Ubuntu 16.04 x64上进行的安装。

是我的姿势不对，还是存在Bug呢？
错误可以复现。

![issue](https://user-images.githubusercontent.com/16831613/39664909-b95c504c-50bd-11e8-963b-a77ba8efd958.png)

![issue2](https://user-images.githubusercontent.com/16831613/39665158-526f3160-50c2-11e8-9273-842e0b1ad6b1.png)

**Comment by virusdefender** [comment]
fixed in https://github.com/QingdaoU/OnlineJudge/commit/ab37c98347ebaf847a7e9e48ac8df5ae4e88f179
