### ISSUE TITLE
如何使用我自己修改的前端

### ISSUE THREAD

**Issue by SimonHu-HN** [QingdaoU/OnlineJudge#148]
我使用的是 https://github.com/QingdaoU/OnlineJudgeDeploy/tree/2.0 一键部署，我想修改前端样式，于是我git下来的onlinejudge_FE，请问修改之后该如何在我现在已经在本地部署好的网站上显示，还是说使用一键部署好的OJ是没办法自己更新前端源码的？

**Comment by MingqiHuang** [comment]
一键部署脚本有赖于docker-compose.yml文件提供的镜像。一个可行的操作是：先使用npm构建项目，等构建完成后把dist文件夹下的所有内容复制到oj-backend镜像里，然后进入oj-backend镜像运行deploy目录下的entrypoint.sh脚本，运行完了之后就给前端打好patch了。

如果需要以后都使用修改后的前端，直接``docker commit oj-backend``然后把docker-compose.yml文件中指定的镜像修改为commit输出的sha512即可。

**Comment by SimonHu-HN** [comment]
@MingqiHuang OK,我试一下，thx

**Comment by MingqiHuang** [comment]
@SimonHu-HN 如果需要更多帮助可以随时at我，我可以提供一份比较完整的Instructions.

**Comment by SimonHu-HN** [comment]
@MingqiHuang 麻烦你就在个问题这里弄一份比较完整的Instructions.吧，这个问题也可以被更多人看到，帮助更多人解答。Thank you very much

**Comment by MingqiHuang** [comment]
@SimonHu-HN 比较关心您按照我的方法能不能正常更新前端源码

**Comment by virusdefender** [comment]
感觉楼主看二楼的办法的第一段就够了

**Comment by MingqiHuang** [comment]
@SimonHu-HN 是的。

**Comment by SimonHu-HN** [comment]
@MingqiHuang  done，thanks a lot^_^

**Comment by MingqiHuang** [comment]
[OnlineJudge 前端二次开发指北](https://github.com/QingdaoU/OnlineJudge/files/1997577/Instructions.pdf)

很抱歉，由于我不会用Markdown，所以只能用LaTeX写了一份说明，希望能帮到更多的人。

**Comment by virusdefender** [comment]
稍后会把这个文档整理到 https://docs.onlinejudge.me/

感谢 @MingqiHuang
