### ISSUE TITLE
How to add more language support, such as Ruby 

### ISSUE THREAD

**Issue by merlinv** [QingdaoU/OnlineJudge#149]
Beside of  C, C++, Java, ... I want to add more language support such as Ruby or Javascript 
Could you please tell me how to do that ? what module should I change or update?

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/blob/master/judge/languages.py

For test environment, you can set `seccomp_rule= None`

**Comment by merlinv** [comment]
@virusdefender  how does it works with OnlineJudgeDeploy ?
Actually I want to modify some features and run it on my local.

**Comment by eagle705** [comment]
In addition, [1] you should add compiler(e.g Ruby??) to your judge_server.
[2] modify https://github.com/QingdaoU/OnlineJudge/blob/master/judge/languages.py
then, it will work
