### ISSUE TITLE
'Make public' does not work when I share problems in contest to open problems list

### ISSUE THREAD

**Issue by eagle705** [QingdaoU/OnlineJudge#152]
I'm trying to share my problems in contest section.

I clicked **Make public** button, and I inserted display ids that is not duplicated.

then, alert **"Already be a public problem"** appeared. However the problem is not shown on the problems in open list.

is this a bug?

**Comment by virusdefender** [comment]
`Already be a public problem` is an error message, for the reason that it is added from the public problem set, you can not put it back again.

**Comment by not-tanh** [comment]
In my case, I made the problem public, but then I deleted it. It won't work when I make it public again. 
I think it should have worked right? Can I do anything manually to make it public again?
