### ISSUE TITLE
Is there any way to show stdout (result of code) in problem.vue ?

### ISSUE THREAD

**Issue by eagle705** [QingdaoU/OnlineJudge#153]
Hello, 

I'm still working on adding new functions to your awesome OnlineJudge website.

Thanks to you, I added C# compiler, change editor and etc.

Now, I want to add some <div> DOM which can show the result of code in problem.vue for providing more information before routing to another result page.

I have a plan to add Run button.
is there any way to get the result before user submit the code?

**Comment by virusdefender** [comment]
You can set `output=True` to get submission output

https://github.com/QingdaoU/OnlineJudge/blob/master/judge/dispatcher.py#L149

If you want to use the input data from user, like test run function, more code should be added to judge server

**Comment by virusdefender** [comment]
It seems you have many constructive ideas, What kind of instant messaging do you use? 

wechat? telegram? or others? Maybe you can get a quicker reply

**Comment by eagle705** [comment]
I'm using telegram (username: "eagle705") :) Thank you for your quick reply.
As you mentioned, ``òutput=True```give me the result. However I can see it. When I logged in "admin". How can I get this json data when I logged in non-admin?
the json data looks like
```
"info": {
            "err": null,
            "data": [
                {
                    "error": 0,
                    "score": 50,
                    "memory": 1503232,
                    "output": "3",  <-- I want to get it
                    "result": 0,
                    "signal": 0,
                    "cpu_time": 0,
                    "exit_code": 0,
                    "real_time": 1,
                    "test_case": "1",
                    "output_md5": "eccbc87e4b5ce2fe28308fd9f2a7baf3"
                }]
          }
```

**Comment by virusdefender** [comment]
You need to change the source code of this repo

**Comment by eagle705** [comment]
Last week, I'm trying to change the source code and I found something about ```_judger.run```. 
As I know,  ```_judger```is a wrapper for compiler module. In this api, testcase must be feeded. 
![image](https://user-images.githubusercontent.com/7252598/41951017-d8570c3e-7a03-11e8-99e2-f50277f9c7a5.png)
However, I just want to compile a source code without any testcase.    
In order to do that, I think 
[1] I should modify  ```_judger```module or
[2] I add fake testcase. 

Am I right?

**Comment by virusdefender** [comment]
- If you just want to `compile a source code`, no test case file is needed, because you only need a compiler https://github.com/QingdaoU/JudgeServer/blob/master/server/compiler.py

 - If you means to run a source code without a fixed test case file
   - if you'd like to develop online input function like leetcode, the most simple way is to create a test case file dynamically
   - if the source code do not need input/output, you can use `/dev/null` as input/output file path
