### ISSUE TITLE
Too slow run "docker-compose up -d " at AWS(Amazon Web Services)

### ISSUE THREAD

**Issue by suakii** [QingdaoU/OnlineJudge#157]
Dear Developer,
I have been tested your OnlineJudge at aws freetier.
Everything is ok but when I run "docker-compose up -d" problem happens.
All is too slow to run.

Maybe problem server image url is start with "registry.c-hangzhou....."

How can i fix this problem?

Anyone using aws not happen this problem?

**Comment by virusdefender** [comment]
You can use docker hub image

https://hub.docker.com/u/qduoj/dashboard/
