### ISSUE TITLE
为什么会出现这样的问题？

### ISSUE THREAD

**Issue by fanyuxi2002** [QingdaoU/OnlineJudge#16]
我在执行docker build -t judger /home/OnlineJudge/dockerfiles/judger/这个的时候，为什么到一半的时候会出现
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/trusty-proposed/main/source/Sources  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
这样的问题？

**Comment by virusdefender** [comment]
closed？解决了么？

应该是网络的问题吧。

第一个办法是在 Dockerfile 里面把

```
RUN rm /etc/apt/sources.list
ADD sources.list /etc/apt/
```

删掉重新build试试。

这样会用 Ubuntu 自带的源，可能速度比较慢。比较适合国外的服务器。

另外一个办法是自己改一下代码中的sources.list文件，换成国内的非阿里云的源。版本是Ubuntu 14.04 64位。

**Comment by fanyuxi2002** [comment]
我换成了我的服务器提供商腾讯云的源然后就可以了，谢谢。

**Comment by fanyuxi2002** [comment]
不好意思，又有一点问题想请问一下。
为什么我的运行中的容器列表里面又找不到judger了呢？
root@VM-193-110-ubuntu:/home# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                           PORTS                      NAMES
c95e30405124        oj_web_server       "/bin/sh -c 'bash /co"   42 minutes ago      Up 42 minutes                    127.0.0.1:8080->8080/tcp   home_oj_web_server_1
0796f97e9745        redis               "/entrypoint.sh redis"   42 minutes ago      Up 42 minutes                    6379/tcp                   home_redis_1
a385dd420f78        mysql               "/entrypoint.sh mysql"   48 minutes ago      Up 48 minutes                    3306/tcp                   home_mysql_1
43374fc443fd        c6b2dadbc8ee        "/bin/sh -c 'apt-get "   About an hour ago   Exited (100) About an hour ago                              furious_brown
70b2529780b6        c6b2dadbc8ee        "/bin/sh -c 'apt-get "   About an hour ago   Exited (100) About an hour ago                              awesome_bohr
936985b164bf        c6b2dadbc8ee        "/bin/sh -c 'apt-get "   About an hour ago   Exited (100) About an hour ago                              focused_kilby
7a42a1ce8172        c6b2dadbc8ee        "/bin/sh -c 'apt-get "   2 hours ago         Exited (100) 2 hours ago                                    gloomy_archimedes
527047318b99        c6b2dadbc8ee        "/bin/sh -c 'apt-get "   2 hours ago         Exited (100) 2 hours ago                                    jovial_mirzakhani
6e8f920b3d3f        c6b2dadbc8ee        "/bin/sh -c 'apt-get "   2 hours ago         Exited (100) 2 hours ago                                    happy_knuth

**Comment by fanyuxi2002** [comment]
请问那个启动启动判题服务器那里的RPC Token又是什么呢？

**Comment by virusdefender** [comment]
judger是手动启动的，你确定启动了么？在文档的后半部分。

rpctoken就是密码，防止别人知道了你判题服务器的ip端口后被利用。

**Comment by fanyuxi2002** [comment]
哦，我现在已经启动了judger，而且也配置好了admin里面的“判题服务器”可是，为什么现在提交还是Waiting呢？

**Comment by virusdefender** [comment]
@fanyuxi2002  这不好说。可能是队列没跑起来之类的原因。

你exec进入容器内看看运行`ps -ef`看看。

**Comment by fanyuxi2002** [comment]
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 01:55 ?        00:00:00 /bin/sh -c python server.py
root         6     1  0 01:55 ?        00:00:00 python server.py
root         7     0  0 02:03 ?        00:00:00 /bin/bash
root        20     7  0 02:03 ?        00:00:00 ps -ef

**Comment by virusdefender** [comment]
@fanyuxi2002 

额，不好意思，是 oj_web_server 的那个容器。

**Comment by fanyuxi2002** [comment]
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Feb17 ?        00:00:00 /bin/sh -c bash /code/dockerfiles/oj_web_server/run.sh
nobody       6     1  0 Feb17 ?        00:00:13 /usr/local/bin/python2 /usr/local/bin/supervisord
nobody      13     6  0 Feb17 ?        00:00:10 /usr/local/bin/python2 /usr/local/bin/gunicorn oj.wsgi:application -b 0.0.0.0:8080 --reload
nobody      61    13  2 Feb17 ?        00:16:49 /usr/local/bin/python2 /usr/local/bin/gunicorn oj.wsgi:application -b 0.0.0.0:8080 --reload
root        93     0  0 02:06 ?        00:00:00 /bin/bash
root        98    93  0 02:07 ?        00:00:00 ps -ef

**Comment by virusdefender** [comment]
@fanyuxi2002 

确实，celery没跑起来。

你先试试 `docker restart oj_web_server`，如果还不行就去看看log文件夹中`task_queue.log`和`supervisord.log`里面有什么报错信息么，然后贴上来。

**Comment by fanyuxi2002** [comment]
可以了，已经可以正常评测了，重启docker之后就没问题了，万分感谢。
