### ISSUE TITLE
Re-judge submissions after changing test data

### ISSUE THREAD

**Issue by IcicleF** [QingdaoU/OnlineJudge#160]
I'd like to re-judge the submissions to a certain problem after changing its test data.

Unfortunately this seems to be impossible. May I ask whether there is a way to do so?

**Comment by virusdefender** [comment]
It's easy to do, you can submit a new task to judge and the result will be updated

https://github.com/QingdaoU/OnlineJudge/blob/b33e2db7e9bab08f4581dc20d487e9a50dc12490/submission/views/admin.py#L8
