### ISSUE TITLE
judge_server 在判断java经常失败

### ISSUE THREAD

**Issue by qwganker** [QingdaoU/OnlineJudge#163]
Compiler runtime error, info: {"exit_code": 0, "error": 0, "cpu_time": 3340, "memory": 56221696, "signal": 0, "result": 1, "real_time": 2224}

Compiler runtime error, info: {"exit_code": 0, "error": 0, "cpu_time": 4328, "memory": 56942592, "signal": 9, "result": 1, "real_time": 2707}

偶尔会成功一次

**Comment by zema1** [comment]
可能是机器性能比较差导致的编译超时

result的值得意义可以看这里 https://docs.onlinejudge.me/#/judgeserver/api?id=result-field-return-value

**Comment by qwganker** [comment]
@zema1  但是我在后台的运行时间设置那里值设得很大。另外，我是在点击提交代码后等待大概 7 秒左右的时间就报错了

**Comment by virusdefender** [comment]
这个和后台那里的时间没关系，是编译超时，这个稍后看下怎么解决比较好。

**Comment by qwganker** [comment]
只有unlimit才行
