### ISSUE TITLE
There is an incorrect access control vulnerability that can write file anywhere

### ISSUE THREAD

**Issue by plusls** [QingdaoU/OnlineJudge#165]
The online Judge's sandbox have an incorrect access control vulnerability that can write file anywhere.
User can get the directory list and write it to /tmp. At last user can leak file data by #include

such as:
```C++
#include "/tmp/datafile"
```

There is my test submit: 
[creat file](https://qduoj.com/status/4e2df90b1ec6707cc5da3bac91daa596)
[leak data](https://qduoj.com/status/853fb93178864da2e3a0339e6eb897ef)

**Comment by virusdefender** [comment]
那几个系统调用还没加限制，主要修改了下目录权限。
