### ISSUE TITLE
请问现在这个系统可以部署到 Daocloud 上吗？

### ISSUE THREAD

**Issue by Shuenhoy** [QingdaoU/OnlineJudge#17]
补充：
今天看了一下GoOnlineJudge 可以通过 https://github.com/ZJGSU-Open-Source/docker-oj 来直接部署到daocloud
请问这个系统可以用类似的方式部署到 daocloud 上吗

**Comment by virusdefender** [comment]
理论上是可以的，但是我没试过，因为完全是Docker的架构。

数据库之类的放在上面不是很放心。

**Comment by virusdefender** [comment]
update:

试了一下，有个别不是很兼容的写法。比如开放端口必须在Dockerfile中声明，不声明的就设置中开放端口会导致部署失败。其实本地运行Docker是可以只在运行参数中写端口的。

```
2016-02-19 20:12:53:Start app failed. "Errinfo:%!(EXTRA *errors.errorString=Image has no any exposed port, you should expose a port in Dockerfile)"
```

还有里面的Volume好像只能映射一个路径，而且不能是根路径，如果我的应用需要写`/var`和`/etc`就没法全部映射了。应该不是我的用法不对。

![qq20160219-0 2x](https://cloud.githubusercontent.com/assets/4939404/13175771/9bfce7ce-d747-11e5-9315-542ba6277784.png)

还有MySQL貌似没有web界面，管理起来不是很方便。

综上所述，暂时无法兼容，但是修改起来也不难。

<del>DaoCloud给点赞助费可以考虑下。</del>

**Comment by imcaffrey** [comment]
我应该怎样修改呢？

**Comment by virusdefender** [comment]
@imcaffrey 这个问题我在问DaoCloud的人，先等等看。

**Comment by imcaffrey** [comment]
恩谢谢

**Comment by imcaffrey** [comment]
@wph95

**Comment by WPH95** [comment]
1. 并没有看懂问题出在哪里啊
2. https://github.com/ZJGSU-Open-Source/docker-oj  这个项目的一个主要作者在 daocloud 所以肯定兼容 daocloud
3. 规范的项目需要在 Dockerfile 里声明端口，这个并没有什么错
4. Daocloud 应用那里有 phpmyadmin，绑定了你的 Mysql 就可以来管理数据库
5. Volume 和 mount 比较类似，映射而不是文件，配置文件请用 dockerfile 搞定

还是把问题说明清楚，我去直接找对口的人解决

**Comment by imcaffrey** [comment]
谢谢！

**Comment by virusdefender** [comment]
@WPH95

Volume的我说的不清楚，比如说我想把 `/etc/xxx/`和`/var/xxx/`的目录都映射出去，应该怎么配置。

**Comment by virusdefender** [comment]
update:
 - dockerfile里面增加端口映射
 - 增加自动创建数据库的脚本

未完成
 - Volume相关挂载代码

暂时close

**Comment by yowenter** [comment]
@virusdefender 
Volume的我说的不清楚，比如说我想把 /etc/xxx/和/var/xxx/的目录都映射出去，应该怎么配置。


你好，现在挂载volume 仅支持 挂载一个目录  。
如果您需要挂载两个目录的话，则需要创建两个volume 服务。
