### ISSUE TITLE
行尾空格去除部分bug (judgeserver)

### ISSUE THREAD

**Issue by haixinxu** [QingdaoU/OnlineJudge#177]
判题系统无法正常处理行尾空格。

        user_output_file = os.path.join(self._submission_dir, str(test_case_file_id) + ".out")
        with open(user_output_file, "r", encoding="utf-8") as f:
            content = f.read()
        output_md5 = hashlib.md5(content.rstrip().encode("utf-8")).hexdigest()
        result = output_md5 == self._get_test_case_file_info(test_case_file_id)["stripped_output_md5"]
        return output_md5, result
在content字符串中存储的是整个文件的内容（多行），而Python字符串的.rstrip()函数是删除**字符串尾**的空格，也就是说只有最后一行的行尾空格被删除，而其他行会保留行尾空格进行hash。可以一行一行处理（我不懂Python）。

**Comment by zema1** [comment]
这是预期行为  https://qduoj.com/FAQ
```
About presentation error?
There is no presentation error in this oj.The judger will trim the blacks and wraps in your ouput's last line. if it's still different with the correct output, the result will be Wrong Answer.
```
