### ISSUE TITLE
希望能够更改spj的编写方式。

### ISSUE THREAD

**Issue by CSQingyu** [QingdaoU/OnlineJudge#178]
目前的spj支持读入标准输入和用户输出。建议能够增加读取标准输出（标准答案）的功能。

简单来说，假如有一个计算a*b的题目，那么只需要编写：
-------1.in-------
1.1 1.1
------------------

-------1.out-----
1.21000000000
------------------

-----user.ans----
1.21000009999
------------------

这样，spj可以读取1.in和1.out，并根据1.out判断user.ans的合法性，省去spj编写的困难。

**Comment by virusdefender** [comment]
这个方法可能并不够通用

 - 很多 spj 并不很好给出近似的标准输出的答案
 - user.ans 其实可以硬编码到 spj 代码中
