### ISSUE TITLE
TIME_LIMIT_EXCEEDED 並不會立即中止

### ISSUE THREAD

**Issue by secret104278** [QingdaoU/OnlineJudge#179]
假如今天丟一段while無限的code，例如
```c++
int main() {
    int a;
    while(true) {
        a++;
    }
}
```
然後max cpu time限制為10ms之類的
雖然說result會是`CPU_TIME_LIMIT_EXCEEDED`
但是會得到類似以下的輸出
``` json
{
  "error": 0,
  "real_time": 999,
  "output_md5": null,
  "cpu_time": 996,
  "memory": 1507328,
  "exit_code": 0,
  "result": 1,
  "signal": 9
}
```
也就是說process實際上跑了996ms才被`SIGKILL`，這樣子如果一般的題目max cpu time設為1000ms，情況就會更嚴重，judge會變得沒有效率。
這樣子的情況是為什麼呢？感謝大大

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/Judger/blob/newnew/src/child.c#L57
https://github.com/QingdaoU/Judger/blob/newnew/src/runner.c#L135

https://linux.die.net/man/2/setrlimit

>     RLIMIT_CPU
> CPU time limit in seconds

`setrlimit` 只能使用秒作为单位，所以需要先向上取整得到秒数，然后最后检查使用的时间和设定值是否一致
