### ISSUE TITLE
提交结果System Error怎么解决

### ISSUE THREAD

**Issue by xunixH** [QingdaoU/OnlineJudge#18]
在同一个服务器上配置判题，在/admin界面设置好了判题服务器是127.0.0.1，端口8085,密码正确，返回结果是System Error: [Errno 111] Connection refused，如果在docker-compose文件上设置ip为公网ip，返回结果是System Error: [{"result": 7}, {"result": 7}]

**Comment by virusdefender** [comment]
我试了一下，docker-compose中是0.0.0.0:8080:8085，后台设置是公网ip:8085是可以成功的。

你先测试一下。

关于地址绑定，我有空更新下文档，说的确实不是太对。

**Comment by virusdefender** [comment]
admin如果配置是127.0.0.1，这将会是容器内部的本地地址，而不是服务器上的本地地址。

**Comment by xunixH** [comment]
我试了依然是哪个System Error: [{"result": 7}]的错误。每次提交的时候都会有“您选择的代码语言可能存在错误，是否继续提交？”的提醒，编译错误能够正确显示

**Comment by virusdefender** [comment]
> 您选择的代码语言可能存在错误，是否继续提交？

这个可以先忽略

你看下log文件夹中有没有什么错误信息啊

**Comment by xunixH** [comment]
😬是我把内存限制调的太小了。。。log显示不能小于16m，我调过之后就好了，thanks

**Comment by virusdefender** [comment]
额，对，这个地方前后端还不统一。抽空fix，谢谢~

**Comment by virusdefender** [comment]
其实16M内存也太小了，建议512M以上。因为没有为Java单独设置策略，太小的话，jvm都无法启动。

**Comment by xunixH** [comment]
一般ACM题目限制都是两位数吧，不过还好我们很少用java

**Comment by virusdefender** [comment]
不是Java就足够了
