### ISSUE TITLE
spj支持輸出分數而不只是對錯

### ISSUE THREAD

**Issue by secret104278** [QingdaoU/OnlineJudge#180]
目前的spj只能夠判斷一筆測資是否對錯
是否有計畫支援可以輸出judge的分數？
因為像是project類型的題目，需要讀學生submission的輸出，然後算出一個分數。
當前的架構有辦法支援嗎？

或是我可以幫忙加上這個功能，可能就spj src裡面可以cout這筆測資的分數，然後去讀judger的output之類的

**Comment by virusdefender** [comment]
但是这一套东西怎么去和现在的测试用例分组给分互相兼容呢。要分为三种了么

 - ACM 模式
 - OI 分组固定给分
 - spj 给分

**Comment by secret104278** [comment]
分類可能還要再確認一下

不過我是打算先改Judge Server，因為我現在有個project會從這裡開始接

**Comment by secret104278** [comment]
@virusdefender 我覺得可以在 Judge Server 的 spj judge 的 response 多加一個 `"spj_output" 提供spj運行的輸出內容。
這樣如果 backend 那邊有需要這些資料就可以抓過去用，應該還滿彈性的吧

**Comment by zema1** [comment]
spj_output 在一些题目中可能多达几M 几十M，这样不妥的。
