### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by gamijin0** [QingdaoU/OnlineJudge#182]
批量上传题目压缩文件时文件稍微大一些(6M)就会报这个错;
看到/app/deploy/nginx/api_proxy.conf 中已经写了client_max_body_size 200M;
请问如何解决这个问题?

浏览器是chrome ,页面的提示为 "Upload failed",查看浏览器日志是 "413 Request Entity Too Large"

**Comment by zema1** [comment]
你是不是用nginx 又包了一层，这个server是直接暴露外网的么

**Comment by gamijin0** [comment]
啊，没错，就是这个原因，不实在好意思了，非常感谢🙏🏻
