### ISSUE TITLE
创建题目过程中的问题

### ISSUE THREAD

**Issue by NJUJYB** [QingdaoU/OnlineJudge#183]
在进行题目创建的时候：
1）内存、时间的限制最好加上单位，看了代码才知道内存限制单位是MB，且范围是1-1024；
2）提交的测试用例必须要在压缩包中，且以1.in, 1.out开始的顺序。感觉并没有必要非要从1开始，只要字符对应就行，因为对于一个题目来说测试用例有时并没有先后顺序的影响；
3）或是可以增加关于提交文件格式的说明；
希望这几点可以进行改进。

**Comment by zema1** [comment]
1) 我觉得可以加上单位，至于范围限制无所谓，想限制多少限制多少  https://github.com/QingdaoU/OnlineJudgeFE/pull/35
2) 的确，判题时测试用例的顺序不影响结果。只是每个 oj 都有自己的规范，做一些限制，方便做合法检查，减少bug。而且在这个 oj 的 `1.in`,`1.out` 的格式和判题时的部分逻辑有耦合的，不方便作改动。
3) 提交格式说明在文档里有
