### ISSUE TITLE
添加对反代的支持

### ISSUE THREAD

**Issue by felinae98** [QingdaoU/OnlineJudge#188]
有的时候服务器中需要运行多个服务，可能需要使用反向代理，客户端到反代容器使用https，反代容器到后端使用http。
如果启用了force_https，会出现无限301的情况。可以通过识别X-Forwarded-Proto或者X-Forwarded-Ssl头实现（改下nginx配置文件应该行
而且后端显示的IP是反代容器的IP，可以同时识别X-Real-Ip或者X-Forwarded-For实现

**Comment by virusdefender** [comment]
- ip 头是支持的，可以修改 docker-compose 环境变量（只支持正确的 ip， xff 的多 ip 不支持） https://github.com/QingdaoU/OnlineJudge/blob/master/deploy/entrypoint.sh#L34
 - https 建议前置反代来解决

**Comment by felinae98** [comment]
thx
