### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by b04901066** [QingdaoU/OnlineJudge#189]
執行以下程式，永遠都是 Compile Error
UnicodeDecodeError :'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

但是這應該是WA才對，
因此造成說十筆測資中，
只要有一筆輸出的char是不合法的，
就連部分正確分數都沒有。
`
#include<iostream>
int main(){
   std::cout << char(-1);
}
`
执行以上程式，永远都是 Compile Error
UnicodeDecodeError :'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

但是这应该是WA才对，
因此造成说十笔测资中，
只要有一笔输出的char是不合法的，
就连部分正确分数都没有。

**Comment by zhblue** [comment]
建议检查是否有中文字符，如空格标点出现在源码中。

**Comment by b04901066** [comment]
確定沒有
但是cout出來的東西是亂碼
我想說可能是judge判斷的寫法造成這種問題

**Comment by b04901066** [comment]
可以嘗試在任意題目中輸出奇怪的char
結果都會是Compile Error
而非WA

可以尝试在任意题目中输出奇怪的char
结果都会是Compile Error
而非WA

**Comment by zhblue** [comment]
编译错误一般来说都还没有进入judge阶段，要编译通过才会judge.
建议关闭输入法，重新输入一遍上面的源码，不要用复制粘贴的。
复制粘贴的时候会带有不可见的非法字符。

**Comment by b04901066** [comment]
所以我才要發issue啊
就是因為理論上可以編譯
但卻是Compile Error
您可在任意c++題目中cout << char(-1);
應該都會是這個結果

所以我才要发issue啊
就是因为理论上可以编译
但却是Compile Error
您可在任意c++题目中cout << char(-1);
应该都会是这个结果

**Comment by zhblue** [comment]
您试试在这个地方是否编译错误。
http://hustoj.com/oj/wx2.php

**Comment by b04901066** [comment]
可以編譯並正常執行

可以编译并正常执行

**Comment by virusdefender** [comment]
已修
