### ISSUE TITLE
测试部署说明中命令有拼写错误

### ISSUE THREAD

**Issue by fydpfg** [QingdaoU/OnlineJudge#19]
http://qingdaou.github.io/OnlineJudge/easy_install.html

cp OnlineJudge/oj/custom_setting.example.py OnlineJudge/oj/custom_setting.py
这条命令中，文件名的setting都应该是settings

**Comment by virusdefender** [comment]
十分感谢，已经改过来了。

http://qingdaou.github.io/OnlineJudge/easy_install.html?clear_cache=1
