### ISSUE TITLE
Add Sample问题

### ISSUE THREAD

**Issue by Straw-Breeze** [QingdaoU/OnlineJudge#191]
在`Create Problem`中，想添加第二组 Sample 时候发现，那个`Add Sample`按钮不在 Sample 版块，而是被挪到了 Hint 版块下面，依稀记得在 6 月份的版本是没有这个 Bug 的，希望能及时修复一下！

**Comment by Straw-Breeze** [comment]
> 在`Create Problem`中，想添加第二组 Sample 时候发现，那个`Add Sample`按钮不在 Sample 版块，而是被挪到了 Hint 版块下面，依稀记得在 6 月份的版本是没有这个 Bug 的，希望能及时修复一下！

Bug 图片 ![img](http://thyrsi.com/t6/612/1542771845x2890211732.jpg)

**Comment by zema1** [comment]
了解了 之前手贱移动了一下..

**Comment by zema1** [comment]
https://github.com/QingdaoU/OnlineJudgeFE/pull/35
