### ISSUE TITLE
Bug:用户可以绕过contest权限检查提交不可见的比赛题目

### ISSUE THREAD

**Issue by HandsomeHow** [QingdaoU/OnlineJudge#195]
有一contest设置了权限,A账号有权限查看题目排行榜等,B账号无权限。

在一浏览器内打开两个窗口登录A账号（窗口X 窗口Y）,然后窗口X进入contest后打开题目页面编辑代码,然后去窗口Y注销A账户登录B账户,回到窗口X提交代码,

最终的结果为没有权限的B账号提交了这个题,并在排行榜上和提交记录都有记录.

**Comment by virusdefender** [comment]
@zema1

**Comment by HandsomeHow** [comment]
上述步骤只是简单复现,实际上的话对于密码保护的contest可以利用上述这一点直接进行post请求来提交,只要猜一猜display id就行
