### ISSUE TITLE
可否在启动OJ的同时不影响已有的web服务？

### ISSUE THREAD

**Issue by hatsune-miku** [QingdaoU/OnlineJudge#198]
在部署OJ之前，我已有一个nginx指向/var/www/html
部署时，因为docker内好像自己也有一个nginx，两个nginx在80和443端口上冲突
如果停掉我自己的nginx，OJ可以顺利使用，但是这就导致我自己的页面不能显示

我尝试修改了docker-compose.yml，将
ports:
      - "0.0.0.0:80:8000"
改为
      - "0.0.0.0:8081:8000"
然后重新compose

但是我访问 http://my_site.com:8081 仍然不行

请问有没有一种办法，可以将OJ部署到类似 http://my_site.com/oj/ 这样，
在启动OJ的同时不影响已有的web服务？

**Comment by virusdefender** [comment]
你可以选择让你的 Nginx 反向代理到 oj，通过 server_name 区分。

需要修改端口，不过你修改端口的方法是对的，不能访问可能是别的原因。

至于 `/oj` 这种子目录的方法，暂时是不行的。

**Comment by hatsune-miku** [comment]
感谢w
