### ISSUE TITLE
双因素验证不同设备时区设置导致无法验证

### ISSUE THREAD

**Issue by 0x3A2B** [QingdaoU/OnlineJudge#199]
即使Linux时区设置的是UTC+8:00时区, 但是linux上的双因素验证取的是UTC+0:00的时间, 而手机上的时间是UTC+8:00, 手机上微软的Authenticator取的是UTC+8:00时间，导致验证失败。请问该如何修复？

**Comment by virusdefender** [comment]
这个真的和时区有关么，应该是时间戳吧

我看了下我用的库 pyotp 的实现，和时区无关。

验证不通过可能还是时间不对导致的？现在确实写的比较严格，`valid_window` 为 0。

**Comment by 0x3A2B** [comment]
> 这个真的和时区有关么，应该是时间戳吧
> 
> 我看了下我用的库 pyotp 的实现，和时区无关。
> 
> 验证不通过可能还是时间不对导致的？现在确实写的比较严格，`valid_window` 为 0。

可是我把我手机的时区改为UTC+0:00就可以通过验证了，所以我认为是时区问题。

**Comment by virusdefender** [comment]
你是什么手机 app，我觉得这是手机 app 实现的问题。

**Comment by 0x3A2B** [comment]
> 你是什么手机 app，我觉得这是手机 app 实现的问题。

我用的是微软的Authenticator（https://play.google.com/store/apps/details?id=com.azure.authenticator）
Google的两步验证（https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2）我也试了，不行
