### ISSUE TITLE
English

### ISSUE THREAD

**Issue by Nuruddinjr** [QingdaoU/OnlineJudge#2]
Can we use OnlineJudge in English?
How to translate?

**Comment by virusdefender** [comment]
It seems a lot of work.

We will try our best to do it, but we can't guarantee.

If you want to translate by yourself, https://docs.djangoproject.com/en/1.8/topics/i18n/  may do help.

**Comment by virusdefender** [comment]
Sorry to keep you waiting

English version had been released

https://github.com/QingdaoU/OnlineJudge
