### ISSUE TITLE
启动所有容器时，oj_web_server 无法启动

### ISSUE THREAD

**Issue by hanzeil** [QingdaoU/OnlineJudge#20]
运行 docker-compose up -d启动所有容器时，oj_web_server无法启动，mysql和redis都没有问题，
log:
oj_web_server_1 | bash: /code/dockerfiles/oj_web_server/run.sh: No such file or directory
ojwebserver_oj_web_server_1 exited with code 127

**Comment by virusdefender** [comment]
你看下docker-compose.yml里面的路径映射是否与你服务器上的路径一致

**Comment by hanzeil** [comment]
你好，是一样的

**Comment by virusdefender** [comment]
有点奇怪

错误是 `/code/dockerfiles/oj_web_server/run.sh: No such file or directory`

说明容器内没有这个文件，但是我看了下源码中是有的啊。

**Comment by hanzeil** [comment]
OK 搞定了 果然是路径问题，非常感谢！
