### ISSUE TITLE
更新到 Version: 20181215 的問題

### ISSUE THREAD

**Issue by tico88612** [QingdaoU/OnlineJudge#206]
前7天出完比賽題，Special Judge 測試為正常
前3天更新到 Version: 20181215
昨天開比賽的時候，有用到Special Judge的題目，沒有CE的Code全部爆System Error

比賽途中稍微改spj的code推測錯誤點，似乎在這裡
```cpp
input = fopen(args[1], "r");
user_output = fopen(args[2], "r");
if(input == NULL || user_output == NULL){
    printf("Failed to open output file\n");
    close_file(input);
    close_file(user_output);
    return ERROR;
}
```
但不確定是input還是user_output出問題

目前解決是降版處理 Version: 20180815

**Comment by tico88612** [comment]
我現在已經更新上去 Version: 20181215-9a50c
但是剛剛傳送spj題還是System Error

我需要開什麼 log 檔給您看嗎？

**Comment by tico88612** [comment]
test_case: Permission Denied
test_case 資料夾權限是 710

**Comment by virusdefender** [comment]
那就加上 `sudo`

`sudo ls -la OnlineJudgeDeploy/data/backend/test_case/`

**Comment by tico88612** [comment]
裡面資料夾權限全都是 710
除了回上層的資料夾以外

**Comment by virusdefender** [comment]
你是怎么更新的啊，只更新了后端没 JudgeServer ？

**Comment by tico88612** [comment]
backend是自建docker
JudgeServer是照OnlineJudgeDeploy

**Comment by virusdefender** [comment]
所以你的 backend 或者 JudgeServer 有些代码没跟上？

**Comment by tico88612** [comment]
OnlineJudgeDeploy 的 部分Code 沒有跟上的樣子
剛剛有更新了
現在是CE
spj説IOError
一般題會說failed to create runtime dir

**Comment by virusdefender** [comment]
那是你的 docker-compose.yml 没跟上

**Comment by tico88612** [comment]
Backend 我每次都會載新的版本，然後 docker build .
JudgeServer 都是用 docker-compose.yml 的預設

應該是OK的吧？

**Comment by virusdefender** [comment]
嗯，反正尽量是整套更新而不是只更新部分就好

**Comment by tico88612** [comment]
本來就有加這行了，但還是會出現這訊息

**Comment by tico88612** [comment]
找到問題了
JudgeServer docker image 沒更新
```
docker-compose pull
```
還以為啟動的時候會更新docker image
我對 docker 不熟悉
更新完已解決
