### ISSUE TITLE
OJ backend is always using port 80

### ISSUE THREAD

**Issue by McDic** [QingdaoU/OnlineJudge#207]
I edited the config .yml file to make oj-backend to use port 8081 and confirmed via `sudo docker-compose config`.

![image](https://user-images.githubusercontent.com/19789019/50414249-d3cb3e00-0857-11e9-9a05-6e4ab074e28a.png)

After that I restarted docker-compose using `sudo docker-compose restart` and checked using ports via `sudo netstat -ntlp`

![image](https://user-images.githubusercontent.com/19789019/50414362-797ead00-0858-11e9-9f42-41bb0ce68b79.png)

Docker is still using port 80. How can I change the port to use?

**Comment by virusdefender** [comment]
you need `docker-compose up -d`, restart will not re-create containers

**Comment by McDic** [comment]
For your information, I am running this on AWS EC2, Ubuntu 18.04.

**Comment by McDic** [comment]
Can I configure HTTPS protocol just by putting `*.pem` files in `data/backend/ssl/.well-known` folder? If not, where can I know the syntax of `/.well-known/pki-validation/fileauth.txt` and other necessary files?

**Comment by virusdefender** [comment]
If you already have ssl cert files (`server.key` and `server.crt`), the only work is to put them in `OnlineJudgeDeploy/data/backend/ssl/`

**Comment by McDic** [comment]
I overrided `server.crt` and `server.key` by `fullchain.pem` and `privkey.pem` generated by [certbot](https://letsencrypt.readthedocs.io/en/latest/using.html#where-are-my-certificates) then did `docker exec -it oj-backend sh -c "cd /app/deploy; supervisorctl restart nginx"` but it doesn't worked. I got banned from letsencrypt server due to the reached limit of calls, so if my approach is right I will try again after 7~8 days from now.

**Comment by virusdefender** [comment]
> but it doesn't worked

You mean the browser is still using the old cert ?
