### ISSUE TITLE
使用Python写Special Judge

### ISSUE THREAD

**Issue by yuan776** [QingdaoU/OnlineJudge#213]
在线文档 http://docs.onlinejudge.me/#/ 里面提到了可以使用C来写Special Judge, 请问OnlineJudge是否支持python写Special Judge. 如果没有这样的功能, 如何添加是比较好的方式.

**Comment by virusdefender** [comment]
参考已有实现即可

https://github.com/QingdaoU/JudgeServer/blob/master/server/judge_client.py#L65
