### ISSUE TITLE
在choose_judge_server函数中有可能产生死锁

### ISSUE THREAD

**Issue by michaelzf** [QingdaoU/OnlineJudge#218]
![image](https://user-images.githubusercontent.com/5130512/51435059-3de5d000-1caa-11e9-980e-19be76863f57.png)

因为是根据task_number做的排序，并发量大的时候可能会产生死锁

当同时有A和B两个任务执行的时候，如果他们获取的judge_server间隔，task_number有变化，
得到的judge_server顺序不一致，A得到的顺序是judge_server1,judge_server2，B的到的顺序是
judge_server2，judge_server1，如果没有执行到save操作，结果有可能是A锁住了judge_server1，
去获取judge_server2，B锁住judge_server2去获取judge_server1，这就会产生死锁现象。

**Comment by virusdefender** [comment]
感谢

数据库的 select_for_update 保证不会有两个查询同时进入截图上的 49 行，需要一个结束 transaction 另外一个才会结束阻塞。本身不存在一个被锁住另外一个还没被锁住的情况。

有问题随时回复~

**Comment by michaelzf** [comment]
我这边对python和django都没有那么熟悉，但是试验过，48行并没有查询数据，49号才会实际查询，所以会导致死锁
