### ISSUE TITLE
并发可能导致同一个用户的同一个考试产生多条ACMContestRank

### ISSUE THREAD

**Issue by michaelzf** [QingdaoU/OnlineJudge#219]
https://github.com/QingdaoU/OnlineJudge/blob/f7bd9f16b44f944e0bb370dcc7e0e82a1f2b5eb4/judge/dispatcher.py#L327

ACMContestRank没有设置唯一索引，同一个用户有可能创建出多条数据。之后get就会一直抛出异常

**Comment by virusdefender** [comment]
感谢，这个问题已经修复了。

https://github.com/QingdaoU/OnlineJudge/blob/master/judge/dispatcher.py#L343

https://github.com/QingdaoU/OnlineJudge/blob/master/contest/models.py#L77
