### ISSUE TITLE
求单独分离 判题服务器 

### ISSUE THREAD

**Issue by Rainboylvx** [QingdaoU/OnlineJudge#22]
能不能把  判题服务器  单独分离出了为一个项目?这都是OJ的核心

**Comment by virusdefender** [comment]
本来就是分离的啊

沙箱在这 https://github.com/QingdaoU/Judger

admin后台可以添加判题服务器的ip

![qq20160317-0 2x](https://cloud.githubusercontent.com/assets/4939404/13836899/ffcb93b4-ec40-11e5-8bac-722c6c0e8334.png)

**Comment by Rainboylvx** [comment]
对不起 我眼瞎了 我会好好用这个的 @_@
