### ISSUE TITLE
文档http://docs.onlinejudge.me现在好像不能访问，所以只能提问，我的oj正常启动 ，但是当我登陆的时候提示server error

### ISSUE THREAD

**Issue by nicitian** [QingdaoU/OnlineJudge#223]
在提交issue之前请

  - 认真阅读文档 http://docs.onlinejudge.me/#/
  - 搜索和查看历史issues
  - 安全类问题请不要在 GitHub 上公布，请发送邮件到 `admin@qduoj.com`，根据漏洞危害程度发送红包感谢。
 
然后提交issue请写清楚下列事项
 
  - 进行什么操作的时候遇到了什么问题，最好能有复现步骤
  - 错误提示是什么，如果看不到错误提示，请去data文件夹查看相应log文件。大段的错误提示请包在代码块标记里面。
  - 你尝试修复问题的操作
  - 页面问题请写清浏览器版本，尽量有截图

**Comment by nicitian** [comment]
并且，我在管理页登陆的时候无法登陆而且也是显示“server error ” 
是因为我用的是windows  + docker吗？感觉上是前端的问题啊....

**Comment by HandsomeHow** [comment]
看看日志？

**Comment by nicitian** [comment]
> 看看日志？
额，请问
日志保存在什么位置？

**Comment by nicitian** [comment]
> 看看日志？

我看了一下OnlineJudgeDeploy\data\backend\log目录下面的日志文件貌似都没有问题应该是前端的问题

**Comment by virusdefender** [comment]
日志应该是有问题的，贴一下吧
