### ISSUE TITLE
关于fps题目导入的问题

### ISSUE THREAD

**Issue by DistanceYatogami** [QingdaoU/OnlineJudge#229]
服务器是腾讯云学生机
系统版本Ubuntu 18.04 LTS
导入FPS题目时提醒server error

**Comment by zhblue** [comment]
去服务器上看/var/log/nginx/error.log

**Comment by virusdefender** [comment]
可能是 parse 的问题，麻烦上传一下那个文件我看下。

先 close 可以继续在这里讨论。
