### ISSUE TITLE
OI模式数据未上传产生CE的问题

### ISSUE THREAD

**Issue by usernameisnotalraedytaken** [QingdaoU/OnlineJudge#230]
建议在前端Demo上显示信息，比如“数据未上传”。另外，为了防止这种问题（我们机房的老师经常忘记加数据），建议在创建题目那里判断一下有没有上传数据。

**Comment by usernameisnotalraedytaken** [comment]
![捕获](https://user-images.githubusercontent.com/42826126/54485704-64924280-48b8-11e9-9100-05b6aad80b03.PNG)

如图

**Comment by virusdefender** [comment]
有判断啊，但是之后为啥丢了测试数据？

**Comment by virusdefender** [comment]
测试数据偶尔会丢貌似是一个神奇的bug，暂时不清楚，如果有任何问题可以再继续回复。
