### ISSUE TITLE
Problems导入问题（Server error）

### ISSUE THREAD

**Issue by FlameStar9527** [QingdaoU/OnlineJudge#238]
上传QDUOJ Problems与FPS Problems经常会出现Server error问题

Nginx没有报错（错误日志没有提示）；Testcase文件上传正常；判题系统正常（A+B 
problems测试）；QDUOJ导出Problems正常

操作环境：
1.阿里云主机（学生机）和DigitalOcean（配置和前者相似）都试过了
2.操作系统 Ubuntu 16.04.3 LTS
3.上传的Problems：QDUOJ导出的Problems（QDUOJ），交流群里的谭浩强老师的C程序设计课后题（FPS），hustoj的测试样例（FPS）

操作步骤：
1.重置服务器
2.安装LNMP（宝塔和军哥的都试了）
3.严格按照OnlineJudgeDeploy中步骤进行
4.进入后台，进行导入Problems操作，失败
![001](https://user-images.githubusercontent.com/48273375/55601541-f5f82480-5793-11e9-8227-b1a78a7bc1f8.png)

**Comment by virusdefender** [comment]
尝试修了一下，你更新看看。

有问题可以继续回复。

**Comment by FlameStar9527** [comment]
成功了，题目可正常导入，也可以正常测试。
感谢大佬。

**Comment by liuxuehao** [comment]
请问这个导入的题目又没有什么样例呀

**Comment by zhblue** [comment]
https://github.com/zhblue/freeproblemset/tree/master/fps-examples

**Comment by ttzytt** [comment]
遇到同样的问题了

**Comment by ttzytt** [comment]
> 有问题可以继续回复。

你好，我遇到了同样的问题，请问当时是怎么解决的

**Comment by TJ111m** [comment]
还是相同的问题，上传之后显示server error
