### ISSUE TITLE
头像无法上传

### ISSUE THREAD

**Issue by Steve-George** [QingdaoU/OnlineJudge#241]
用户上传头像时会卡在最后一步

**Comment by CPH-Technology** [comment]
点完upload后无反应

**Comment by CPH-Technology** [comment]
https://qduoj.com/这上也是

**Comment by Harry-zklcdc** [comment]
我这里可以上传啊，记得这个bug之前修复过了

**Comment by CPH-Technology** [comment]
windows自带的edge不行，但是chrome可以






------------------ 原始邮件 ------------------
发件人: "Harry-zklcdc"<notifications@github.com>;
发送时间: 2019年5月3日(星期五) 凌晨3:32
收件人: "QingdaoU/OnlineJudge"<OnlineJudge@noreply.github.com>;
抄送: "Steve George"<1312580942@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [QingdaoU/OnlineJudge] 头像无法上传 (#241)




我这里可以上传啊，记得这个bug之前修复过了

**Comment by Harry-zklcdc** [comment]
edge会有莫名其妙的错误，请使用最新版火狐或者chrome
