### ISSUE TITLE
Test case not found when trying to submit

### ISSUE THREAD

**Issue by Muhammad-Al-Halaby** [QingdaoU/OnlineJudge#242]
I'm getting this error "Test case not found" when trying to submit codes to any problem.

I tried deleting problems and creating them again, I also checked "OnlineJudgeDeploy/data/backend/test_case" and it's totally empty, although I can download the test cases of each problem from "localhost/admin/problems" page. 

I'm sure I uploaded the test cases in a correct way cause it's not my first time and I've used the system before.

I hope you can provide a fast solution (even if temporary).

![test-case-not-found](https://user-images.githubusercontent.com/6758797/56873520-2483bb00-6a33-11e9-8c9f-e37a8878d666.png)

**Comment by virusdefender** [comment]
please submit the result of `docker inspect oj-backend`

**Comment by Muhammad-Al-Halaby** [comment]
the result of `docker inspect oj-backend`

`[
    {
        "Id": "5f653d1c6733510eb93a7c89952c15d00bafc1f510cbef88619c08e080f6e8e0",
        "Created": "2019-04-19T07:19:04.212304395Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "/app/deploy/entrypoint.sh"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2152,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-04-29T00:20:49.48970126Z",
            "FinishedAt": "2019-04-29T00:19:01.722086287Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2019-04-29T04:13:35.835200049+02:00",
                        "End": "2019-04-29T04:13:36.131254699+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-04-29T04:13:41.317636445+02:00",
                        "End": "2019-04-29T04:13:41.636257622+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-04-29T04:13:46.745037687+02:00",
                        "End": "2019-04-29T04:13:47.037443729+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-04-29T04:13:52.137352058+02:00",
                        "End": "2019-04-29T04:13:52.449734751+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-04-29T04:13:57.614625884+02:00",
                        "End": "2019-04-29T04:13:57.917845386+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:94f897d973780f3233401e5773f026855ae0b6f1181bc6ce9529d663dbb5316f",
        "ResolvConfPath": "/var/lib/docker/containers/5f653d1c6733510eb93a7c89952c15d00bafc1f510cbef88619c08e080f6e8e0/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/5f653d1c6733510eb93a7c89952c15d00bafc1f510cbef88619c08e080f6e8e0/hostname",
        "HostsPath": "/var/lib/docker/containers/5f653d1c6733510eb93a7c89952c15d00bafc1f510cbef88619c08e080f6e8e0/hosts",
        "LogPath": "/var/lib/docker/containers/5f653d1c6733510eb93a7c89952c15d00bafc1f510cbef88619c08e080f6e8e0/5f653d1c6733510eb93a7c89952c15d00bafc1f510cbef88619c08e080f6e8e0-json.log",
        "Name": "/oj-backend",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/mu/OnlineJudgeDeploy/data/backend/dist:/app/dist:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "onlinejudgedeploy_default",
            "PortBindings": {
                "1443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "443"
                    }
                ],
                "8000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/615b98c79ce3fa2cf2d30c28f36c7270003448f315d13500df34c5da8aef5bc2-init/diff:/var/lib/docker/overlay2/3e6f2ce9474ad77c26bff8b892b08c851204969d347f55f496a99e1a1675c050/diff:/var/lib/docker/overlay2/a47d3ec46b5838fb99c82b091c0401a875892baa84af59aecc1e306541275367/diff:/var/lib/docker/overlay2/8b66e44e50c7e63513d0338768676648d21e8ace330487d2d1fa363b7cb289c8/diff:/var/lib/docker/overlay2/13744eb6b78bcf1c6e6fe5fbb516aa633601cb6382e917e4d17d5def602b14f5/diff:/var/lib/docker/overlay2/e2333e4267c1fb7f15617d6e109aa56a72029554fb6ee47050b6f18371e6f01f/diff:/var/lib/docker/overlay2/04794f821d4407f3c1a685a332c513d009048c33e3ebe91b7553985e9980ecd5/diff:/var/lib/docker/overlay2/0a24e5d983548d735916b6dda5dcfcb04756670168b0e61e41bd1b41cbcaa4a0/diff:/var/lib/docker/overlay2/794163186ab724937ae71cbe315d6230e98718f49fd57e6ca2a59d01d981dd87/diff",
                "MergedDir": "/var/lib/docker/overlay2/615b98c79ce3fa2cf2d30c28f36c7270003448f315d13500df34c5da8aef5bc2/merged",
                "UpperDir": "/var/lib/docker/overlay2/615b98c79ce3fa2cf2d30c28f36c7270003448f315d13500df34c5da8aef5bc2/diff",
                "WorkDir": "/var/lib/docker/overlay2/615b98c79ce3fa2cf2d30c28f36c7270003448f315d13500df34c5da8aef5bc2/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/mu/OnlineJudgeDeploy/data/backend/dist",
                "Destination": "/app/dist",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "5f653d1c6733",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1443/tcp": {},
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "JUDGE_SERVER_TOKEN=CHANGE_THIS",
                "POSTGRES_PASSWORD=onlinejudge",
                "POSTGRES_USER=onlinejudge",
                "POSTGRES_DB=onlinejudge",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.7.3",
                "PYTHON_PIP_VERSION=19.0.3",
                "OJ_ENV=production"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "python2 /app/deploy/health_check.py"
                ],
                "Interval": 5000000000,
                "Retries": 3
            },
            "ArgsEscaped": true,
            "Image": "registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend",
            "Volumes": {
                "/app/dist": {}
            },
            "WorkingDir": "/app",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "/app/deploy/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "f3882b41679194ee1394c81dc05fece0334d01a99ecf0c99c1831976c525ff59",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "onlinejudgedeploy",
                "com.docker.compose.service": "oj-backend",
                "com.docker.compose.version": "1.17.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "821c276a8e9e91475b847e9b44d3cd556960fbf384c2b5ed32928d7c3f7522b9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "443"
                    }
                ],
                "8000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/821c276a8e9e",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "onlinejudgedeploy_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "5f653d1c6733",
                        "oj-backend"
                    ],
                    "NetworkID": "01e3e893e0d29cc6cbbb166069aa9e0afc0daf25e26b208ba92537623210f049",
                    "EndpointID": "7d5bf7bc2c3fe0f8ebb4db4694228b89e7a3c3ed5cfb35b9a76dea5beea45d80",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
`

**Comment by virusdefender** [comment]
It seems that you do not mount the `OnlineJudgeDeloy/data` into the container?

Have you edited `docker-compose.yml`？

**Comment by Muhammad-Al-Halaby** [comment]
> It seems that you did not mount the `OnlineJudgeDeloy/data` into the container?
> 
> Have you ever edited `docker-compose.yml`？

Yes, I have. I needed to change a minor issue in the Front-End so I followed the documentation to install OnlineJudgeFE and do the necessary steps.

Is there a quick fix for the problem you mentioned?

**Comment by Muhammad-Al-Halaby** [comment]
I added back `- ./data/backend:/data`,  ran `docker-compose up -d` the result `Recreating oj-backend ... done`

I can now upload test cases, they go in the right place and the error is no longer there. 

Thank you for your fast response, you've been a great help!
