### ISSUE TITLE
Is it possible to view a mapping between IDs and IP addresses?

### ISSUE THREAD

**Issue by thomas-hugel** [QingdaoU/OnlineJudge#247]
Hi,
First, congratulations for this wonderful tool!
In order to fight against fraud, I wonder whether it is possible to have a mapping between the IDs used and the IP addresses of the contestants.
Thanks.

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/blob/9869f6294c04504093c964e218f5f8e3b41e4186/account/views/oj.py#L333

but you still write some extra code to implement this function
