### ISSUE TITLE
支持封榜嘛？

### ISSUE THREAD

**Issue by tabris233** [QingdaoU/OnlineJudge#248]
RT

**Comment by tico88612** [comment]
請看說明文件
https://docs.onlinejudge.me/#/onlinejudge/guide/contest_rule_type

**Comment by tabris233** [comment]
> 請看說明文件
> https://docs.onlinejudge.me/#/onlinejudge/guide/contest_rule_type

所以这个需要在比赛中人工进行 调整的对吧？  
可以在比赛前就设置好嘛？

**Comment by tico88612** [comment]
> 所以这个需要在比赛中人工进行 调整的对吧？

要人工調整

> 可以在比赛前就设置好嘛？

看起來是沒辦法

**Comment by tabris233** [comment]
> > 所以这个需要在比赛中人工进行 调整的对吧？
> 
> 要人工調整
> 
> > 可以在比赛前就设置好嘛？
> 
> 看起來是沒辦法

好的 了解了 3q
