### ISSUE TITLE
Error running compiler in lrun

### ISSUE THREAD

**Issue by swapteam** [QingdaoU/OnlineJudge#25]
原来其他服务器弄的judger容器搬到其他服务器运行出现Error running compiler in lrun

**Comment by virusdefender** [comment]
你的代码是哪一年的了？

早不用lrun了，如果没有数据，最好重新看教程部署一遍。

**Comment by swapteam** [comment]
应该是今年年初的代码,新的judger容器和原来的ojweb代码兼容吗

**Comment by virusdefender** [comment]
因为前期开发快读迭代，我也不太好说了。数据应该是兼容的，代码不兼容。

如果数据比较多，建议留下联系方式，我们一起看下。

**Comment by swapteam** [comment]
数据库兼容就行,我pull下代码,还有judger的容器pull好慢...用的dao pull

**Comment by virusdefender** [comment]
数据库可能是兼容的，主要取决于安装时间。

**一定先备份所有代码和数据库还有测试用例！**

pull代码后尝试 `python manage.py migrate`

**Comment by virusdefender** [comment]
因为自动安装脚本里面涉及到创建配置文件，创建数据库之类的，自动安装很可能会失败。如果有问题，可以再继续评论。

**Comment by virusdefender** [comment]
升级后fixed

同期修补的问题见 https://github.com/QingdaoU/OnlineJudge/issues/26
