### ISSUE TITLE
更改language.py后发生的问题

### ISSUE THREAD

**Issue by zhuyuanzy** [QingdaoU/OnlineJudge#255]
OJ版本Version: 20190326-74644
在修改编译选项，将oj-backend中/judge/language.py的部分内容修改为以下内容

`
"max_cpu_time": 10000,                                                                                          
    "max_real_time": 20000,                                                                             
    "max_memory":8* 1024 * 1024 * 1024,                      
    "compile_command": "/usr/bin/g++ -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++14 {src_path} -lm -o {exe_path}"`
并`SysOptions.reset_languages()`后，在网页上编译cpp的spj程序时出现了以下问题
![avatar](http://chuantu.xyz/t6/702/1564481059x1031866013.png)

**Comment by virusdefender** [comment]
感觉是 judger 运行出错了，导致输出了一个非法的 json，建议再认真对比下你修改的对么？

**Comment by virusdefender** [comment]
先 close 了，有任何问题可以继续回复。
