### ISSUE TITLE
编译器出错该怎么解决

### ISSUE THREAD

**Issue by Akvicor** [QingdaoU/OnlineJudge#258]
Compile Error
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.

**Comment by Akvicor** [comment]
![Snipaste_2019-08-28_23-51-38](https://user-images.githubusercontent.com/24453010/63871768-1351b780-c9ef-11e9-96ce-bf6d83144b7e.png)

**Comment by ICEYSELF** [comment]
通常来说，gcc编译器内部存在一些bug导致其进入某种死循环并且无限分配内存，或者编译一些十分复杂的代码，导致内存耗尽(gcc非常耗内存)，操作系统就会把gcc杀死。
鉴于你使用gcc5，而这个版本在编译eigen和realsense时确实出现了一定问题，你可以尝试在服务器上编译代码，然后开一个htop来观测资源消耗。
如果确定是gcc的问题，你可以把编译器替换为内存更友好的clang，或者升级gcc版本。
FYI

**Comment by Akvicor** [comment]
> 通常来说，gcc编译器内部存在一些bug导致其进入某种死循环并且无限分配内存，或者编译一些十分复杂的代码，导致内存耗尽(gcc非常耗内存)，操作系统就会把gcc杀死。
> 鉴于你使用gcc5，而这个版本在编译eigen和realsense时确实出现了一定问题，你可以尝试在服务器上编译代码，然后开一个htop来观测资源消耗。
> 如果确定是gcc的问题，你可以把编译器替换为内存更友好的clang，或者升级gcc版本。
> FYI

系统的gcc版本是gcc7 我该如何更换judger的gcc版本？

**Comment by Akvicor** [comment]
同样的代码在ssh中，使用与OJ相同的编译参数，没有发生任何问题

**Comment by ICEYSELF** [comment]
> 同样的代码在ssh中，使用与OJ相同的编译参数，没有发生任何问题
试试在ssh环境中使用gcc -v确定版本号(不出意外应该是7.3)，docker里的OJ系统使用的应该并非是系统gcc(应该是5.4)
可以把代码贴上来，我试着复现一下

**Comment by Akvicor** [comment]
https://pasteme.cn/15317

**Comment by Akvicor** [comment]
![image](https://user-images.githubusercontent.com/24453010/63907139-e3d19800-ca4c-11e9-84f6-d77b5ebb4ba1.png)

系统的gcc我升到了7.4

**Comment by Akvicor** [comment]
> > 同样的代码在ssh中，使用与OJ相同的编译参数，没有发生任何问题
> 
> 试试在ssh环境中使用gcc -v确定版本号(不出意外应该是7.3)，docker里的OJ系统使用的应该并非是系统gcc(应该是5.4)
> 可以把代码贴上来，我试着复现一下

我在https://qduoj.com/上试了一发，一点事没有，正常编译通过

**Comment by Akvicor** [comment]
> > 同样的代码在ssh中，使用与OJ相同的编译参数，没有发生任何问题
> 
> 试试在ssh环境中使用gcc -v确定版本号(不出意外应该是7.3)，docker里的OJ系统使用的应该并非是系统gcc(应该是5.4)
> 可以把代码贴上来，我试着复现一下

我发现，加上这个函数就会报上面的那种编译错误，不加就没事

![image](https://user-images.githubusercontent.com/24453010/63929880-cf10f680-ca84-11e9-9251-d59654f6b44e.png)

**Comment by Akvicor** [comment]
> > 同样的代码在ssh中，使用与OJ相同的编译参数，没有发生任何问题
> 
> 试试在ssh环境中使用gcc -v确定版本号(不出意外应该是7.3)，docker里的OJ系统使用的应该并非是系统gcc(应该是5.4)
> 可以把代码贴上来，我试着复现一下

难道说是因为给编译器的内存太小了？还是其他什么玄学的问题？

**Comment by ICEYSELF** [comment]
我试着reproduce一下

**Comment by ICEYSELF** [comment]
> 难道说是因为给编译器的内存太小了？还是其他什么玄学的问题？
编译过程中峰值内存消耗约为300MiB

**Comment by Akvicor** [comment]
> > 难道说是因为给编译器的内存太小了？还是其他什么玄学的问题？
> 
> 编译过程中峰值内存消耗约为300MiB

我看了源码，OJ是只给了编译器128MiB的内存吗？

**Comment by virusdefender** [comment]
尝试给编译器更长的运行时间https://docs.onlinejudge.me/#/onlinejudge/guide/update_compile_options

**Comment by virusdefender** [comment]
先 close 了，有任何问题可以继续回复。

新版本已经增加部分语言的编译时间和内存占用限制。
