### ISSUE TITLE
SPJ题目编译错误（json）

### ISSUE THREAD

**Issue by Akvicor** [QingdaoU/OnlineJudge#259]
![image](https://user-images.githubusercontent.com/24453010/64022127-1d4af600-cb68-11e9-91b3-23379f3921af.png)

![image](https://user-images.githubusercontent.com/24453010/64022140-26d45e00-cb68-11e9-8321-a989963f8810.png)

**Comment by Akvicor** [comment]
https://qduoj.com/problem/73

qduoj上也是编译错误。

![image](https://user-images.githubusercontent.com/24453010/64025517-6c485980-cb6f-11e9-8a95-cde6286364e4.png)

**Comment by virusdefender** [comment]
你好，感谢反馈，问题已经修复，稍后将更新版本~

**Comment by riteme** [comment]
现在最新版本的依然有这个问题，包括 QDUOJ 上的那道 SPJ 测试题。请问确实是修复了吗？

如果没有修复，请问我该如何降级到一个没有问题的 OJ 版本？
