### ISSUE TITLE
有办法在比赛题里面添加题目列表里面的题吗

### ISSUE THREAD

**Issue by swapteam** [QingdaoU/OnlineJudge#26]
有些题在测试比赛的时候要用很多次,有没有办法直接添加原来添加过的题目到比赛中

**Comment by virusdefender** [comment]
现在并不行。只能比赛题目添加到公开题目中。

我觉得以后可以考虑用VJ。

**Comment by swapteam** [comment]
刚刚更新之后可以登入,但是现在发现oj无法登入了,新注册的用户也无法登入,提示用户名密码错误

**Comment by virusdefender** [comment]
这个不好说啊。你新注册一个看看也这样么

**Comment by virusdefender** [comment]
你migrate数据库还有重新打包js了么？

**Comment by swapteam** [comment]
嗯.

**Comment by virusdefender** [comment]
这不大好说。加我qq  1670873886 看下

**Comment by virusdefender** [comment]
修正管理员重置密码的bug https://github.com/QingdaoU/OnlineJudge/commit/657b7c4f5119fc2c7e586b9d026456a2720ab7f9  

by@spxcds
