### ISSUE TITLE
如何讓每一題執行特定的TestMain.java而不是直接執行使用者上傳的程式？

### ISSUE THREAD

**Issue by kerorojason** [QingdaoU/OnlineJudge#266]
如題，假設我不想要讓系統直接執行使用者上傳的main function，
要如何在批改系統每一題各自有不同的TestMain.java，
再利用這個TestMain.java內的main function呼叫使用者的class？

我目前的想法是修改judge/languages.py內的compile_command 和run 的command，
然後在server/compiler.py內替換{test_main}成當下批改的題號，
但是在compiler.py內我讀取不到problem id，
還有其他推薦的方法嗎？
謝謝

**Comment by virusdefender** [comment]
后台有一个 code template 的功能，可以编写自己的代码，然后让用户做填空，类似 leetcode 那种。
