### ISSUE TITLE
群发邮件

### ISSUE THREAD

**Issue by william-song-shy** [QingdaoU/OnlineJudge#267]
您好，我想知道有没有什么简单的方法用配置的SMTP邮箱想所有或指定的部分用户发送邮件，好像后台没有这个功能？如果没有，您能不能添加一下这个功能？多谢！

**Comment by virusdefender** [comment]
这个和 oj 无关啊，需要群发可以自己导出数据然后自己使用 smtp 发送。

有问题可以继续回复。

**Comment by william-song-shy** [comment]
多谢
请问如何设置让管理员加入排行榜？


---原始邮件---
发件人: &quot;LiYang&quot;<notifications@github.com&gt;
发送时间: 2019年9月22日(星期日) 下午2:36
收件人: &quot;QingdaoU/OnlineJudge&quot;<OnlineJudge@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;william-song-shy&quot;<2560814258@qq.com&gt;;
主题: Re: [QingdaoU/OnlineJudge] 群发邮件 (#267)



这个和 oj 无关啊，需要群发可以自己导出数据然后自己使用 smtp 发送。
 
有问题可以继续回复。
 
&mdash;
