### ISSUE TITLE
SMTP密码未保存，注册无法使用邮箱验证

### ISSUE THREAD

**Issue by qyy2003** [QingdaoU/OnlineJudge#273]
![图片](https://user-images.githubusercontent.com/41172859/66709979-c577ef80-eda1-11e9-9901-fabb9cd375cb.png)
![图片](https://user-images.githubusercontent.com/41172859/66709988-e6d8db80-eda1-11e9-81ea-86bb9fc6a005.png)
SendTestEmailSuccess,刷新完以后SMTP的密码没有保存，用户注册仍然不需要邮箱验证.已试过重启，无效
![图片](https://user-images.githubusercontent.com/41172859/66709997-1f78b500-eda2-11e9-8c6f-d10b633cec67.png)

**Comment by tico88612** [comment]
SMTP 密碼本來就不會直接顯示

你應該保存完先按 Send Test Email

**Comment by qyy2003** [comment]
我Send Test Email了，也收到了，但仍然不能验证

**Comment by qyy2003** [comment]
难道注册用户不可邮箱验证吗？

**Comment by 2512821228** [comment]
邮箱验证是在找回密码的时候才有用

**Comment by qyy2003** [comment]
可是root不是可以直接改密码吗？

**Comment by 2512821228** [comment]
这个oj是没有邮箱验证注册这个功能的

**Comment by qyy2003** [comment]
好吧，建议开发一个
