### ISSUE TITLE
能否在“运行超时”的情况下，给出具体的测试用时？

### ISSUE THREAD

**Issue by bhjlll** [QingdaoU/OnlineJudge#281]
在解决第8题“下一个回文数”时，仅做了一点很小的改动，就让原本超时（>1000ms）的程序只花了1ms就完成了测试，使人疑惑。

**Comment by virusdefender** [comment]
你觉得改动了代码就运行快了是预期的么

你得贴一下提交详情的那个时间分布表格

**Comment by william-song-shy** [comment]
如果
```cpp
while (true)
{
}
```
运行时间是多少？

**Comment by bhjlll** [comment]
比较道歉的是，我的水平还很低，暂不清楚如何使用while（ture）来测试运行时间。可以有详细一点的说法嘛？



这是我目前的代码段。现在是使用gets来输入该字符串，之前是使用的while（（a[i++]=getchar（））!='\n'）;两段程序的差异主要也就体现在这一个地方。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LiYang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 晚上10:54
收件人:&nbsp;"QingdaoU/OnlineJudge"<OnlineJudge@noreply.github.com&gt;;
抄送:&nbsp;"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"<1962903043@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QingdaoU/OnlineJudge] 能否在“运行超时”的情况下，给出具体的测试用时？ (#281)




如果
 while (true) { }
 
运行时间是多少？

**Comment by william-song-shy** [comment]
> 比较道歉的是，我的水平还很低，暂不清楚如何使用while（ture）来测试运行时间。可以有详细一点的说法嘛？ 这是我目前的代码段。现在是使用gets来输入该字符串，之前是使用的while（（a[i++]=getchar（））!='\n'）;两段程序的差异主要也就体现在这一个地方。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LiYang"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月1日(星期五) 晚上10:54 收件人:&nbsp;"QingdaoU/OnlineJudge"<OnlineJudge@noreply.github.com&gt;; 抄送:&nbsp;"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"<1962903043@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [QingdaoU/OnlineJudge] 能否在“运行超时”的情况下，给出具体的测试用时？ (#281) 如果 while (true) { } 运行时间是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是指您无法测算死循环的运行时间，因为您评测机跑到世界末日也不会退出程序

**Comment by bhjlll** [comment]
之前没有连接上校园网，就直接使用邮箱回复了，好像没有直接显示在这里。我主要想请问的是，这个系统能不能在运行超时的情况下，依旧给出该程序的运行时间（而不仅仅是“超时警告”），方便我们初学者进行修改呢？对于题目本身我已经没有疑惑了，谢谢学长们。

**Comment by william-song-shy** [comment]
> 之前没有连接上校园网，就直接使用邮箱回复了，好像没有直接显示在这里。我主要想请问的是，这个系统能不能在运行超时的情况下，依旧给出该程序的运行时间（而不仅仅是“超时警告”），方便我们初学者进行修改呢？对于题目本身我已经没有疑惑了，谢谢学长们。

请您告诉我死循环的运行时间，谢谢

**Comment by bhjlll** [comment]
> > 比较道歉的是，我的水平还很低，暂时清楚如何使用while（ture）来测试运行时间。可以有详细一点的陈述嘛？这是我目前的代码段。现在是使用gets来输入该字符串，之前是使用的同时（（A [1 ++] =的getchar（））= '\ n'！）;两段程序的差异主要也就体现在这一个地方
> > [...](#) 
> > --------- ---------原始邮件------------------发件人：“ LiYang” < [notifications@github.com](mailto:notifications@github.com) >; 发送时间：2019年11月1日（星期五）晚上10:54收件人：“ QingdaoU / OnlineJudge” < [OnlineJudge@noreply.github.com](mailto:OnlineJudge@noreply.github.com) >; 抄送：“” < [1962903043@qq.com](mailto:1962903043@qq.com) >;“作者” < [author@noreply.github.com](mailto:author@noreply.github.com) >; （[＃281](https://github.com/QingdaoU/OnlineJudge/issues/281)）如果while（true）{}运行时间是多少？—您收到此消息是因为，您是（？）可以在“运行超时”的情况下，进行特定的测试用时？编写线程。直接回复此电子邮件，在GitHub上查看或取消订阅。
> 
> 我是指您无法测算死循环的运行时间，因为您评估机跑到世界末日也不会退出程序

好的，感谢您的提醒，我可能确实忽略了一些地方。

**Comment by bhjlll** [comment]
> > 之前没有连接上校园网，就直接使用邮箱回复了，好像没有直接显示在这里。我主要想请问的是，这个系统能不能在运行超时的情况下，依旧指定该程序的运行时间（而不仅仅是）仅是“超时警告”），方便我们初学者进行修改呢？对于转化本身我已经没有疑惑了，谢谢学长们。
> 
> 请您告诉我死循环的运行时间，谢谢

我该怎样得到死循环的运行时间呢？（捂脸）

**Comment by virusdefender** [comment]
- 某些情况，比如死循环，比如要运行一万年，是无法得到实际运行时间的
 - 目前 oj 的设计是 cpu 时间向上取整 （设置 1200ms 实际可以运行 2000ms），实际时间同理，然后判断下最终的运行时间和设置的关系。
   - 比如实际运行了 2000ms + 超时 kill，那就是真超时了，真正需要的时间也无从得知。
   - 比如实际运行了 1800ms 加正常结束，那也是超时了，但是可以知道实际的运行时间。这个数据都可以从单个提交的详情页看到。
