### ISSUE TITLE
Injecting analytics scripts

### ISSUE THREAD

**Issue by amphineko** [QingdaoU/OnlineJudge#284]
我们想在 OJ 上注入一些类似下面样例里的统计代码，但是目前只能通过修改 dist 里的已生成文件来实现。

```
<script type="text/javascript" src="https://v1.cnzz.com/z_stat.php?id=114514&web_id=1919810"></script>
```

希望能在管理面板增加一个在所有页面注入任意 HTML 标签的方法。

**Comment by virusdefender** [comment]
可以改下 nginx 的配置文件，然后插入代码

http://nginx.org/en/docs/http/ngx_http_sub_module.html
