### ISSUE TITLE
镜像制作失败

### ISSUE THREAD

**Issue by zengfanpei** [QingdaoU/OnlineJudge#286]
环境：ubuntu 16.04 ， Docker version 18.09.7
问题描述：拉下源代码之后，按照Dockerfile制作镜像，会在第6步卡住报错
期望：能否将这些环境安装 制作到一个基础镜像之内，然后引用该基础镜像
附带三张截图链接：

1.  报错举例：https://s2.ax1x.com/2019/12/17/QIVi6g.png
2.  卡顿超过一天：https://s2.ax1x.com/2019/12/17/QIVKpT.png
3.  网速测试：https://s2.ax1x.com/2019/12/17/QIVQcF.png

**Comment by virusdefender** [comment]
感觉是 alipine 的官方源的问题，可以试试自己替换镜像源

https://mirrors.tuna.tsinghua.edu.cn/help/alpine/
