### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by tiodh** [QingdaoU/OnlineJudge#289]
Try to test the system using basic operation like substraction with maximum memory is 8 MB but the return is runtime error. But when i set the memory to 256 MB submission is accepted.

**Comment by virusdefender** [comment]
this limits all memory used by the process including libs, not only your code, so it need some memory to start

**Comment by tiodh** [comment]
Thank you for the response. How to determine the memory limit?

**Comment by tiodh** [comment]
`a = int(input())
b = int(input())
c = a/b
print(c)`
try to solving this problem but always get runtime error
i try to activating debug in judge-server and debuging the code it give correct result

**Comment by virusdefender** [comment]
i think it should not be lower than 64Mb

**Comment by tiodh** [comment]
`a = int(input())
b = int(input())
c = a/b
print(c)`
trying run this code but the result is runtime error, the memory set to 1024 MB and time limit to 1000
try activating debug mode in judge-server and run that code in /judge/run, code return correct result.

**Comment by virusdefender** [comment]
so what's the output

**Comment by tiodh** [comment]
try run the solution script with input 6 and 3 and the result is 2

**Comment by virusdefender** [comment]
and your input file content?

**Comment by tiodh** [comment]
my input file content is
`6 3`
and my output file content is
`2`
is it right?

**Comment by virusdefender** [comment]
the input should be 
```
6
3
```

**Comment by virusdefender** [comment]
you can use 

```
python x.py < 1.in
```

test your input locally
