### ISSUE TITLE
后台添加题目时的一个BUG

### ISSUE THREAD

**Issue by BIGBALLON** [QingdaoU/OnlineJudge#29]
- 试图在添加题目的时候插入 一段代码

![2016-04-06 12 45 12](https://cloud.githubusercontent.com/assets/7837172/14306100/49997cbc-fbf6-11e5-98ce-033d056998bb.png)

  - 出现如下情况
 
![6 12 45 41](https://cloud.githubusercontent.com/assets/7837172/14306110/5ccd984a-fbf6-11e5-8534-5b7033886267.png)

**Comment by virusdefender** [comment]
这个好像是simditor的问题，我记得见过，我先升级下simditor看看。

**Comment by virusdefender** [comment]
错怪simditor了，我一直以为是它的问题，但是也一直没看。

我发现是xss filter的bug。我看下怎么解决 https://github.com/phith0n/python-xss-filter

**Comment by virusdefender** [comment]
fixed  https://github.com/QingdaoU/OnlineJudge/commit/a5a440b9df9f4aa5882224e061381d8518a7b0d0

https://github.com/phith0n/python-xss-filter/commit/833f67d33a015016b31ac96e41836aa10e5d141a
