### ISSUE TITLE
SMTP发送测试邮件一直在转圈只有就失败了

### ISSUE THREAD

**Issue by zzzzzzz12** [QingdaoU/OnlineJudge#290]
服务器授权码都是对的！就一直转圈圈过了一会·就不转了但没有发送出去[![kphwZs.jpg](https://t1.picb.cc/uploads/2020/03/23/kphwZs.jpg)](https://www.picb.cc/image/kphwZs)

**Comment by renbaoshuo** [comment]
打开 25 和 465 端口

**Comment by zzzzzzz12** [comment]
> 打开 25 和 465 端口

在哪里打开，服务器立吗

**Comment by renbaoshuo** [comment]
> 在哪里打开，服务器里吗

@zzzzzzz12  先关闭容器，修改 `docker-compose.yml` ，在里面增加端口，之后再启动容器。或者选择用支持 `80` 端口发信的邮件服务器，比如 [阿里邮件推送](https://1bs.co/77447407) 这种，推荐第二种。
