### ISSUE TITLE
有人知道如何增加一个导航栏里的内容

### ISSUE THREAD

**Issue by zzzzzzz12** [QingdaoU/OnlineJudge#292]
我想增加一个导航栏里的按钮

**Comment by renbaoshuo** [comment]
https://github.com/QingdaoU/OnlineJudgeFE

**Comment by renbaoshuo** [comment]
看一下这里

**Comment by renbaoshuo** [comment]
https://github.com/QingdaoU/OnlineJudgeFE/blob/master/src/pages/oj/

**Comment by renbaoshuo** [comment]
貌似在这

**Comment by renbaoshuo** [comment]
找到了：https://github.com/QingdaoU/OnlineJudgeFE/blob/master/src/pages/oj/components/NavBar.vue

**Comment by renbaoshuo** [comment]
看看这就行

**Comment by zzzzzzz12** [comment]
> 看看这就行

好的谢谢
