### ISSUE TITLE
Adding support for Rust

### ISSUE THREAD

**Issue by thomas-hugel** [QingdaoU/OnlineJudge#295]
Hi QingdaoU,

Thanks for this wonderful tool.

I would like to add support for the Rust language. It works like C (there is a compiler named rustc).

So I wrote the following config in OnlineJudge/judge/languages.py:
```
_rust_lang_config = {
    "template": """//PREPEND BEGIN
//PREPEND END

//TEMPLATE BEGIN
//TEMPLATE END

//APPEND BEGIN
//APPEND END""",
    "compile": {
        "src_name": "main.rs",
        "exe_name": "main",
        "max_cpu_time": 10000,
        "max_real_time": 20000,
        "max_memory": 1024 * 1024 * 1024,
        "compile_command": "/usr/bin/rustc -O {src_path} -o {exe_path}",
    },
    "run": {
        "command": "{exe_path}",
        "seccomp_rule": None,
        "env": default_env
    }
}
```
and I added it to the subsequent `languages` array.
I also added this config to JudgeServer/client/{go,PHP,Python}.

I also added the rustc compiler to the judge-server Dockerfile and could check that it is properly installed:
```
apt-get install curl && curl https://sh.rustup.rs -sSf | sh -s -- -y && . ~/.cargo/env && ln -s ~/.cargo/bin/rustc /usr/bin/rustc && \
```
However, when I test this configuration on the aplusb problem, I have the following compiler error: 

>  Compiler runtime error, info: {"result": 5, "error": 0, "exit_code": 0, "real_time": 2, "signal": 10, "cpu_time": 0, "memory": 0}

What did I miss? How can I debug it?

Thanks for your help!

**Comment by virusdefender** [comment]
please check `judger.log`

**Comment by thomas-hugel** [comment]
$ cat data/judge_server/log/compile.log 
```
FATAL [2020-04-10 15:54:49] [/tmp/Judger/src/child.c:164]Error: System errno: Permission denied; Internal errno: EXECVE_FAILED
```
On the other hand, the rustc compiler is executable by any user :
```
root@4f0867b505f1:/code# ls -l /usr/bin/rustc 
lrwxrwxrwx 1 root root 22 Mar 14 16:40 /usr/bin/rustc -> /root/.cargo/bin/rustc
root@4f0867b505f1:/code# ls -l /root/.cargo/bin/rustc
-rwxr-xr-x 12 root root 12245112 Mar 14 16:38 /root/.cargo/bin/rustc
```

**Comment by thomas-hugel** [comment]
The permission problem was that there are other users than root which want to use rustc. So I fixed that.
But now I have the following error:
```
FATAL [2020-04-18 14:31:20] [/tmp/Judger/src/child.c:164]Error: System errno: No such file or directory; Internal errno: EXECVE_FAILED
```
I suspect that my previous `_rust_lang_config` is cached somewhere, because the modifications I make to it are not taken into account when I build the container again. Is that true?

**Comment by virusdefender** [comment]
yes, you should run `SysOptions.reset_languages()` in django shell

https://docs.onlinejudge.me/#/onlinejudge/guide/update_compile_options

**Comment by thomas-hugel** [comment]
Now I have the following error at link time:
```
error: linking with `cc` failed: exit code: 1
  = note: collect2: fatal error: ld terminated with signal 25 [File size limit exceeded], core dumped
          compilation terminated.
```
Is there such a limit? Where can I tune it?

**Comment by thomas-hugel** [comment]
I have based the JudgeServer container on Arch Linux, and now it works. Don't ask me why.
I have made my solution available here: https://gitlab.com/qingdaou-online-judge/qingdaou-online-judge-for-rust
Thanks!
