### ISSUE TITLE
qduoj的acm赛制能实现手动封榜吗？

### ISSUE THREAD

**Issue by swust-zyh** [QingdaoU/OnlineJudge#299]
在提交issue之前请

  - 认真阅读文档 http://docs.onlinejudge.me/#/
  - 搜索和查看历史issues
  - 安全类问题请不要在 GitHub 上公布，请发送邮件到 `admin@qduoj.com`，根据漏洞危害程度发送红包感谢。
 
然后提交issue请写清楚下列事项
 
  - 进行什么操作的时候遇到了什么问题，最好能有复现步骤
  - 错误提示是什么，如果看不到错误提示，请去data文件夹查看相应log文件。大段的错误提示请包在代码块标记里面。
  - 你尝试修复问题的操作
  - 页面问题请写清浏览器版本，尽量有截图

**Comment by virusdefender** [comment]
比赛配置里面这个 
![image](https://user-images.githubusercontent.com/4939404/86864208-52689300-c0ff-11ea-9a88-e756f93979cd.png)

注意，开启后不影响管理员视角，请用普通用户测试。
