### ISSUE TITLE
发展建议

### ISSUE THREAD

**Issue by luosiwei-cmd** [QingdaoU/OnlineJudge#300]
Loj 有讨论区，很方便，个人认为讨论区是一个比较重要的功能

用户有各种权限，像lg一样，可以不必删除账号

标签多，页面中文

管理员显示很明显

任何用户都可以添加题目管理审核（这样让供体快一点）

有 Subtask 和捆绑测试

支持语言和题目多

望采纳谢谢！

**Comment by renbaoshuo** [comment]
设置里面可以调中文，强制中文可以去OnlineJudgeFE的源码里改语言配置再build
