### ISSUE TITLE
一个状态列表中的小bug

### ISSUE THREAD

**Issue by gofmartin** [QingdaoU/OnlineJudge#301]
如下图：可以看出标识出来的提交记录并非当前用户的（当前用户仅为普通用户），但是还是可以点击提交的ID查看提交的详细信息，包括提交的源码，不是很清楚这个情况的原因，貌似是概率发生的，

![image](https://user-images.githubusercontent.com/22150665/83329509-8a88e480-a2bc-11ea-9e19-2853cfa922a9.png)

**Comment by Harry-zklcdc** [comment]
用户可以选择是否 share 代码，如果为 share ，普通用户也看得到的

**Comment by gofmartin** [comment]
哦哦原来如此，没注意到还有分享功能
