### ISSUE TITLE
Python 3 code always giving Runtime Error after adding golang support

### ISSUE THREAD

**Issue by beingayush** [QingdaoU/OnlineJudge#305]
After adding support for golang, python3 code always throws Runtime Error

**Comment by beingayush** [comment]
https://qduoj.com/
You can reproduce issue here

**Comment by virusdefender** [comment]
抱歉，稍后看下

**Comment by Rhodanthe1116** [comment]
有同樣問題

**Comment by virusdefender** [comment]
不好意思了，代码已经修复，麻烦重新 pull 一下镜像。

因为是编译选项中写错了，为了避免和自己修改过的编译选项冲突，所以更新过程中不会覆盖这个配置，也就是说只升级镜像不会起作用。

如果没有手动修改过配置，需要按照 https://docs.onlinejudge.me/#/onlinejudge/guide/update_compile_options 来运行一下 `SysOptions.reset_languages()` 才可以 。

如果手动修改过，我就不用多说应该咋做了。
