### ISSUE TITLE
支持修改语言吗？

### ISSUE THREAD

**Issue by kajweb** [QingdaoU/OnlineJudge#306]
1、是否支持中文？
2、Create Problem上传TestCase不友好。
3、IO Mode两个选项有什么区别？
4、建议创建题目加一个Author
5、阿里云Centos安装后，Python默认是3.6，但是编译参数还是3.5，造成py3无法正常编译。
6、

**Comment by renbaoshuo** [comment]
1. 支持中文，设置里面可以调，强制中文请修改源码中语言配置。

**Comment by renbaoshuo** [comment]
3. 你说的应该是OI吧。。。OI/ACM 赛制有区别

**Comment by renbaoshuo** [comment]
5. docker 里面环境都是固定的，不会出现这种情况的吧...

**Comment by kajweb** [comment]
您好，感谢您的耐心解答。刚刚又看了一看，发现是我对这个OJ不熟悉，很多都有相应的解决方案，所以关闭了issues。
3、这个我想问的是Standard IO  &&  File IO的区别
5、环境是我昨天部署的，依据[QingdaoU/OnlineJudgeDeploy](https://github.com/QingdaoU/OnlineJudgeDeploy/tree/2.0)。后来我通过修改编译参数解决了。
![微信截图_20200712025843.png](https://i.loli.net/2020/07/12/KxWizPw9GqgylU2.png)

**Comment by virusdefender** [comment]
https://docs.onlinejudge.me/#/onlinejudge/guide/update_compile_options

https://github.com/QingdaoU/OnlineJudge/issues/305
