### ISSUE TITLE
Python3 always throws runtime error

### ISSUE THREAD

**Issue by praveenkumar-alpha** [QingdaoU/OnlineJudge#308]
python3 throws runtime error even when dealing with hello world program but python2 works fine

**Comment by Harry-zklcdc** [comment]
when did you deploy the Onlinejudge? The Onlinejudge has upgraded these days, and upgraded the Python version. You should use `docker-compose pull && docker-compose up -d` to upgrade it. After upgrading, you should use these command to update language config.

~~~bash
docker exec -it oj-backend sh
python3 manage.py shell
from options.options import *
SysOptions.reset_languages()
exit()
exit
~~~

**Comment by praveenkumar-alpha** [comment]
I deployed OnlineJudge a week back and thanks for the response.

**Comment by Harry-zklcdc** [comment]
It's my honor

**Comment by praveenkumar-alpha** [comment]
It worked thanks a lot !!!!
