### ISSUE TITLE
FILE IO System question

### ISSUE THREAD

**Issue by okcdbu** [QingdaoU/OnlineJudge#309]
hi, I want to know how to use file IO system in this server. Is there any docs or guideline? Please let me know.

**Comment by Harry-zklcdc** [comment]
Are you Upgrade the OnlineJudge recently? Or Install it recently? It has problem in Qduoj's Judger, I have fix it. You can use my revised edition. Follow these steps:

Open `docker-compose.yml`, and Find the `judger_server`, modify the image address to `registry.cn-qingdao.aliyuncs.com/wenjian_oj/judge_server`

**Comment by okcdbu** [comment]
Thanks! It is really helpful to me!

**Comment by youngqqcn** [comment]
Thanks!
