### ISSUE TITLE
关于提交调度

### ISSUE THREAD

**Issue by chenhongqiao** [QingdaoU/OnlineJudge#311]
请问当多个用户同时提交时OnlineJudge的调度策略是什么？所有提交一起测评还是按顺序一个一个来？

**Comment by Harry-zklcdc** [comment]
提交顺序，Redis 队列

**Comment by chenhongqiao** [comment]
我刚刚通过阅读代码发现似乎是每个评测机同时最多运行cpu核心数*2的任务，确认一下是这样吗？

**Comment by Harry-zklcdc** [comment]
是的
