### ISSUE TITLE
联系成为CONTRIBUTOR

### ISSUE THREAD

**Issue by drabbit75** [QingdaoU/OnlineJudge#312]
我是一名软件工程师，因为偶然的缘故看到了这个项目，对于其中的判题的C沙箱代码不是太满意，估计由于历史的原因这份代码有不少冗余，功能上也有缺失，我想成为一名CONTRIBUTOR尝试改进它，看怎么联系

**Comment by virusdefender** [comment]
嗯嗯，看到您的邮件了，我邮件回复你~
