### ISSUE TITLE
[question] 更新程式語言版本 / update language version

### ISSUE THREAD

**Issue by ZoneTwelve** [QingdaoU/OnlineJudge#324]
Hello, because some function only running at new version python, i wish can put an setting for control (compiler/interpreter)'s version.
Or maybe you can just teach me how can i update the judge_server

您好，由於某些功能只有在新版本的 python(3.7/3.8) 上才支援的語法/功能，因此希望可以請您教我如何更新 judge_server 的 程式語言 版本。

謝謝

**Comment by virusdefender** [comment]
修改 judge server dockerfile 中的 python 版本 https://github.com/QingdaoU/JudgeServer/blob/master/Dockerfile

然后更新编译选项 https://github.com/QingdaoU/OnlineJudge/blob/master/judge/languages.py https://docs.onlinejudge.me/#/onlinejudge/guide/update_compile_options
