### ISSUE TITLE
在特定网络环境下所有的 PUT 请求和 DELETE 请求都会出现异常

### ISSUE THREAD

**Issue by catezi** [QingdaoU/OnlineJudge#329]
网络环境：北京某高校的校园网环境

出现问题：由于网络配置当中的某些策略，网站前后端交互所使用的PUT、DELETE请求失效，涉及该两种请求的功能全部无法使用，是否能够添加一项配置，支持将所有的PUT请求和DELETE请求全部转换为POST请求？

**Comment by virusdefender** [comment]
django rest framework 应该有模拟的办法，但是得改前端，如果 waf 是透明代理或者透明桥的话，建议用 https 端口，应该就不会被拦截了。

**Comment by catezi** [comment]
感谢，使用https可以了
