### ISSUE TITLE
wiki bug in 测试开发简易安装文档

### ISSUE THREAD

**Issue by imcaffrey** [QingdaoU/OnlineJudge#33]
`运行 python manage.py celeryd -B -l DEBUG`

Got this
```
Unknown command: 'celeryd'
```

https://github.com/QingdaoU/OnlineJudge/wiki/%E6%B5%8B%E8%AF%95%E5%BC%80%E5%8F%91%E7%AE%80%E6%98%93%E5%AE%89%E8%A3%85%E6%96%87%E6%A1%A3#%E5%90%AF%E5%8A%A8%E9%98%9F%E5%88%97

**Comment by virusdefender** [comment]
已经改过来了，谢谢。

改为`celery -A oj worker --autoscale=30,4 -l DEBUG`
