### ISSUE TITLE
queries reference deleted fields

### ISSUE THREAD

**Issue by sophie200** [QingdaoU/OnlineJudge#346]
Hi, I noticed some of the submission queries still reference problem_id and contest_id, even though they are no longer fields in submission. Is this an error, or is there some special mechanism that prevents errors in these cases? 

(line 74-80) in submission/views/oj.py
https://github.com/QingdaoU/OnlineJudge/blob/master/submission/views/oj.py#L74 
(line 135) in submission/views/oj.py
https://github.com/QingdaoU/OnlineJudge/blob/master/submission/views/oj.py#L135
(line 164) in submission/views/oj.py
https://github.com/QingdaoU/OnlineJudge/blob/master/submission/views/oj.py#L164

**Comment by virusdefender** [comment]
in Django, if a field is `ForeignKey`, you can use both `field_id=number` and `field=SomeModel.objects.get(id=number)`
