### ISSUE TITLE
怎么修改页面显示中文

### ISSUE THREAD

**Issue by nangongfeng1** [QingdaoU/OnlineJudge#347]
用户未登陆前，打开页面是英文菜单，请问怎么修改默认语言

**Comment by renbaoshuo** [comment]
将 https://github.com/QingdaoU/OnlineJudgeFE/blob/master/src/i18n/index.js#L31 处的 `en-US` 替换为 `zh-CN` ，然后重新构建并替换容器内文件即可。

**Comment by nangongfeng1** [comment]
请问，怎么直接修改部署好的文件呢？

**Comment by renbaoshuo** [comment]
可以参考 [文档：修改前端](https://docs.onlinejudge.me/#/onlinejudge/guide/update_fe)
