### ISSUE TITLE
输入和输出个数不一样，测试用例怎么写啊？

### ISSUE THREAD

**Issue by SuWeipeng** [QingdaoU/OnlineJudge#348]
附上例程
```c
#include <stdio.h>
int main(){
  int n;
  int k;
  scanf("%d",&n);
  while(n--){
    int i = 2;
    scanf("%d",&k);
    while(i<=k){
      if(k%i==0){
        if(k!=i){
          printf("%d\r\n",0);
          break;
        }else{
          printf("%d\r\n",1);
        }
      }
      i++;
    } 
  }
}
```

**Comment by SuWeipeng** [comment]
第一个数是循环次数，没有对应的输出。怎么办？

**Comment by virusdefender** [comment]
没懂啥意思，没啥没输出

**Comment by SuWeipeng** [comment]
> 没懂啥意思，没啥没输出

![Snipaste_2021-01-03_18-08-00](https://user-images.githubusercontent.com/24380862/103476208-a9210200-4dee-11eb-89cd-164de992536d.jpg)

**Comment by renbaoshuo** [comment]
这是题目的问题吧...

我觉得你来错地方了，应该去找那个OJ的管理员

**Comment by SuWeipeng** [comment]
> 这是题目的问题吧...
> 
> 我觉得你来错地方了，应该去找那个OJ的管理员

我是在自己写题目自己测试，还不太懂这个 OJ 的判定机制。不会写这个程序的测试用例。试了几次，怎么写都会判断成错的。

**Comment by SuWeipeng** [comment]
就是`输入的个数`与`输出的个数`不一样时，怎么写测试用例能判断是对的呢？

**Comment by SuWeipeng** [comment]
我就是 OJ 的管理员，以前没弄过，刚开始了解。

**Comment by renbaoshuo** [comment]
我觉得您可以先了解一下如何出题。

---

这是正确的样例：

```ini
[input]
2
2
6

[output]
1
0
```

**Comment by SuWeipeng** [comment]
> 我觉得您可以先了解一下如何出题。
> 
> 这是正确的样例：
> 
> ```ini
> [input]
> 2
> 2
> 6
> 
> [output]
> 1
> 0
> ```

第一次我就是这么写的，结果是”Wrong Answer"，附上我的用例。

[000002.zip](https://github.com/QingdaoU/OnlineJudge/files/5761464/000002.zip)

**Comment by SuWeipeng** [comment]
就是上面一开始的程序，写个能跑对的测试用例好难，我都试了 20 次了没有写对。

**Comment by renbaoshuo** [comment]
您的程序也有问题，在 Linux 环境下，换行符是 `\n` (LF) 而非 Windows 下的 `\r\n` (CRLF) 。

下面是修正后的程序：

```cpp
#include <stdio.h>

int main() {
    int n;
    int k;
    scanf("%d", &n);
    while (n--) {
        int i = 2;
        scanf("%d", &k);
        while (i <= k) {
            if (k % i == 0) {
                if (k != i) {
                    printf("%d\n", 0);
                    break;
                } else {
                    printf("%d\n", 1);
                }
            }
            i++;
        }
    }
}
```

**Comment by SuWeipeng** [comment]
> 您的程序也有问题，在 Linux 环境下，换行符是 `\n` (LF) 而非 Windows 下的 `\r\n` (CRLF) 。
> 
> 下面是修正后的程序：
> 
> ```c++
> #include <stdio.h>
> 
> int main() {
>     int n;
>     int k;
>     scanf("%d", &n);
>     while (n--) {
>         int i = 2;
>         scanf("%d", &k);
>         while (i <= k) {
>             if (k % i == 0) {
>                 if (k != i) {
>                     printf("%d\n", 0);
>                     break;
>                 } else {
>                     printf("%d\n", 1);
>                 }
>             }
>             i++;
>         }
>     }
> }
> ```

啊！就是这个问题，对了！对了！终于对了！
