### ISSUE TITLE
Error pulling image (latest) from qduoj/judger

### ISSUE THREAD

**Issue by imcaffrey** [QingdaoU/OnlineJudge#35]
`FATA[2275] Error pulling image (latest) from qduoj/judger, Untar exit status 1 unexpected EOF `

是由于网络原因吗

**Comment by virusdefender** [comment]
你用的哪个，docker hub还是阿里云的？

**Comment by imcaffrey** [comment]
`docker pull qduoj/judger`

**Comment by virusdefender** [comment]
国外的现在国内基本不可用，阿里云的报什么错误

**Comment by imcaffrey** [comment]
我应该需要到5.10号才能回校看log……先关了这个issue吧
