### ISSUE TITLE
前端构建bug

### ISSUE THREAD

**Issue by buaanlsdewm** [QingdaoU/OnlineJudge#350]
你好，输入npm run dev开启前端，有以下报错，在网上找了半天也没解决，麻烦看一下

> onlinejudge@2.0.0 build:dll /home/admin/OJGitLab/OnlineJudgeFE
> webpack --config=build/webpack.dll.conf.js

current version is "20210105-65327"
cleaning old dll..
building ..
Hash: 577694014eac6528860a
Version: webpack 3.12.0
Time: 3336ms
                Asset    Size  Chunks                    Chunk Names
vendor.dll.5776940.js  266 kB       0  [emitted]  [big]  vendor
   [1] (webpack)/buildin/global.js 509 bytes {0} [built]
  [13] dll vendor 12 bytes {0} [built]
  [38] (webpack)/buildin/module.js 517 bytes {0} [built]
  [39] ./node_modules/moment/locale zh-cn 187 bytes {0} [optional] [built]
    + 43 hidden modules

> onlinejudge@2.0.0 dev /home/admin/OJGitLab/OnlineJudgeFE
> node build/dev-server.js

current version is "20210105-65327"
All entries: 
oj
- ./src/pages/oj/index.js

admin
- ./src/pages/admin/index.js

[HPM] Proxy created: /api  ->  http://127.0.0.1:8000
[HPM] Proxy created: /public  ->  http://127.0.0.1:8000
> Starting dev server...
Killed

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/home/admin/node/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! onlinejudge@2.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the onlinejudge@2.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the onlinejudge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs onlinejudge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls onlinejudge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/admin/OJGitLab/OnlineJudgeFE/npm-debug.log

**Comment by Fromnowon** [comment]
![image](https://user-images.githubusercontent.com/2792725/117092720-a4b32880-ad91-11eb-93ba-4fcd170e59e7.png)
