### ISSUE TITLE
File IO 一直Runtime Error

### ISSUE THREAD

**Issue by I-DreamForest-J** [QingdaoU/OnlineJudge#355]
File IO 一直Runtime Error
File IO 一直Runtime Error

**Comment by Fromnowon** [comment]
参考这里：
[https://github.com/QingdaoU/OnlineJudge/issues/309#issuecomment-666298940](url)

**Comment by youngqqcn** [comment]
https://github.com/QingdaoU/OnlineJudge/issues/309

**Comment by I-DreamForest-J** [comment]
Thanks.Had solved.
