### ISSUE TITLE
About Uploading in Heroku

### ISSUE THREAD

**Issue by RedoC-github** [QingdaoU/OnlineJudge#359]
I want to upload this project to Heroku, but I don't know how I can do.
Please tell me is there any way to upload it, please tell me how to if there is.

If there isn't a way, that's ok! Just be free about testing.
Thank you, All of Qingdao University.

**Comment by virusdefender** [comment]
i think is not easy to do so, and i'm not familiar with Heroku.

**Comment by RedoC-github** [comment]
Hmm...

**Comment by RedoC-github** [comment]
Then how can I upload this OJ to the WEB?

**Comment by renbaoshuo** [comment]
You can see: https://github.com/QingdaoU/OnlineJudgeDeploy/blob/2.0/README.en.md

**Comment by RedoC-github** [comment]
I think I should use AWS instead of Heroku

**Comment by RedoC-github** [comment]
@virusdefender @renbaoshuo than what services did you use to publish [qduoj.com](https://qduoj.com/) to web?

**Comment by renbaoshuo** [comment]
> @virusdefender @renbaoshuo than what services did you use to publish [qduoj.com](https://qduoj.com/) to the web?

You can use any server to deploy it.

See: https://github.com/QingdaoU/OnlineJudgeDeploy/blob/2.0/README.en.md

**Comment by virusdefender** [comment]
you should use a normal Linux based server
