### ISSUE TITLE
Feature Request: 增加OI赛制的排名

### ISSUE THREAD

**Issue by htfy96** [QingdaoU/OnlineJudge#36]
有部分分。分数相同时根据罚时排名。

**Comment by virusdefender** [comment]
十分感谢。

但是可能涉及到的改动比较大，已经记在todo list上了，有机会一定做。

**Comment by imcaffrey** [comment]
前排仰慕灰天飞燕！

要是判题能加入OI赛制的部分分功能 那是极好的 :smile:  Thx

**Comment by virusdefender** [comment]
判题部分和OI关系不大，主要是比赛排名和后台编辑。
