### ISSUE TITLE
Test Case "Empty File"

### ISSUE THREAD

**Issue by RedoC-github** [QingdaoU/OnlineJudge#360]
When I upload my test cases to make a problem, I always got an "Empty File" error. I read docs and added info files, but it also failed. How can I submit test cases?

**Comment by virusdefender** [comment]
https://docs.onlinejudge.me/#/onlinejudge/guide/test_case

please submit the output of `unzip -v xxx.zip`

**Comment by RedoC-github** [comment]
Should I have include the info file?

**Comment by RedoC-github** [comment]
OMG, I did it. @virusdefender You're my life-changer!
