### ISSUE TITLE
无法修改网站为默认中文

### ISSUE THREAD

**Issue by Xintnn** [QingdaoU/OnlineJudge#362]
想修改OJ页面为默认中文,想更改只能登录后去设置里改
查看网页文档提示我网页无法连接(ERR_EMPTY_RESPONSE)
自行编译的话会因为无法build而报错
指编译OJ FE前台无法npm build,也无法做镜像 如果npm install会爆error:128错,删掉node_modules爆-2错

**Comment by Xintnn** [comment]
> 想修改OJ页面为默认中文,查看网页文档提示我网页无法连接(ERR_EMPTY_RESPONSE)
> 自行编译的话会因为无法build而报错

指编译OJ FE前台文档无法npm build爆error:128错,删掉node_modules爆-2错

**Comment by undefined-moe** [comment]
这里推荐您使用 [Hydro](https://hydro.js.org) 这套系统，它拥有更多的功能并可以便捷的设置为默认中文。

**Comment by Xintnn** [comment]
已经自行解决()
问题可能出现于我的node和npm版本过高,导致无法install
