### ISSUE TITLE
在Google Chrome上图片无法打开

### ISSUE THREAD

**Issue by shr-NaHCO3** [QingdaoU/OnlineJudge#364]
![屏幕截图 2021-03-24 220723](https://user-images.githubusercontent.com/80567300/112324106-6126c280-8ced-11eb-9bde-6ddda51d9f3f.png)

我在不同的电脑上测试多次，但**_只要用Google Chrome打开，图片就无法显示_**
但是，查阅网页源代码，图片还是可以被打开的：
`<img alt="" src="http://sshd.yangzheng.com.cn:90/JudgeOnline/upload/image/20160107/20160107112840_21554.png">`
不知是代码问题还是Google Chrome的问题？

**Comment by virusdefender** [comment]
https网站不能使用http的资源链接。
