### ISSUE TITLE
如何使用容器的nginx

### ISSUE THREAD

**Issue by cabinary** [QingdaoU/OnlineJudge#374]
我看到了oj-backend里有nginx但是看起来完全没有用上的样子，如果为了保持域关系（防止域错，经常也就用nginx），可能再构建一个其他的docker容器，并开放一个端口给代理使用。这样的话怎么配置才能保证都是只用80/443就完成更多应用的呢？
比如我的网站再开个/api/xxxxx，这可能还走某个asp.net core的应用端口。

**Comment by GiantZwlin** [comment]
你指的是反向代理？

**Comment by virusdefender** [comment]
容器内的 NGINX 有用啊，你可能需要容器外边再搞一个，然后反向代理
