### ISSUE TITLE
我标签填了 但是xianshi显示  Please add at least one tag

### ISSUE THREAD

**Issue by zhangaugust2020** [QingdaoU/OnlineJudge#376]
我标签填了 但是xianshi显示  Please add at least one tag
![image](https://user-images.githubusercontent.com/63038701/126028122-ac0b3e9d-758b-4f20-a529-7189274f22eb.png)

**Comment by ospiper** [comment]
输入Tag后请按回车，才会正确添加标签。

**Comment by zhangaugust2020** [comment]
> 输入标签后请回车，我会添加标签。
已解决，谢谢
