### ISSUE TITLE
报错！！！求安装成功的大神解答！！！

### ISSUE THREAD

**Issue by OIer01** [QingdaoU/OnlineJudge#379]
在运行 pip3 install docker-compose 时报错，内容如下。（经自己测试，开启root权限后仍然报错，内容为Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hm43mki7/cryptography/）
有人能够解决吗？QwQ

<img width="512" alt="屏幕截图 2021-07-27 221114" src="https://user-images.githubusercontent.com/87971412/127169582-a2d50f40-e95f-442f-ac9b-5a826785e7fa.png">

**Comment by renbaoshuo** [comment]
1. 请不要重复开启 issue ，在原 issue 下继续即可。
2. 请截全日志，否则无法准确确定问题之所在。
3. 如需付费代搭建请邮件联系。

**Comment by OIer01** [comment]
**小白不懂Linux**，请问这条命令运行时怎么选择位置？
![捕获](https://user-images.githubusercontent.com/87971412/127273843-e7485d4c-8f5d-442d-9318-61323c5f081d.PNG)

**Comment by OIer01** [comment]
![1](https://user-images.githubusercontent.com/87971412/127276467-9e8937b0-57af-45ec-8656-62938eb7a5fe.PNG)
运行“docker-compose up -d”时，报错如图。请问有人知道怎么回事吗？
