### ISSUE TITLE
新增swift语言时候出现的问题。

### ISSUE THREAD

**Issue by metaire** [QingdaoU/OnlineJudge#385]
在languages内添加了
_swift_lang_config = {
   "run": {
       "exe_name": "t.swift",
       "command": "/usr/bin/swift {exe_path}",
       "seccomp_rule": None,
   }
}
并且在JudgeServer 容器内安装了swift环境，并且在容器内可运行swift代码。（swift也无需编译可运行）
但是最终在项目中运行时，会出现运行时错误。
最终在此次运行的文件地址（在挂载的judege_server/run/run的目标文件中），寻找到一个错误。1.out文件内显示：<unknown>:0: error: unable to open output file '/home/code/.cache/clang/ModuleCache/VXKMIN1Y83K6/SwiftShims-1KFO504FT44T.pcm': 'No such file or directory'
<unknown>:0: error: could not build C module 'SwiftShims'。
请问，该如何解决此项问题？

**Comment by virusdefender** [comment]
这个实际是编译错误吧。

正常情况下，编译器应该是无法写 ` '/home/code/.cache/clang/` 这种路径的，建议把这些缓存路径都配置一下到 `/tmp` 之类的路径下面。

另外为了避免这种编译错误被认为是运行错误，建议和 Python 类似，引入一个编译的过程，也方便看错误。

**Comment by CiyLei** [comment]
> 这实际上是最可能的错误吧。
> 
> 正常情况下，编译器应该是写` '/home/code/.cache/clang/`这种路径的，建议无法将这些路径都配置一下到其`/tmp`类的路径下面。
> 
> 另外是因为避免了这种警告的错误被认为是运行错误，建议和 Python 类似，引入一个警告的过程，也容易看到错误。

试过有效
swiftc编译的时候添加`module-cache-path`参数，比如
```
swiftc -module-cache-path /tmp
```

**Comment by metaire** [comment]
> 这个实际是编译错误吧。
> 
> 正常情况下，编译器应该是无法写 ` '/home/code/.cache/clang/` 这种路径的，建议把这些缓存路径都配置一下到 `/tmp` 之类的路径下面。
> 
> 另外为了避免这种编译错误被认为是运行错误，建议和 Python 类似，引入一个编译的过程，也方便看错误。

好的，本着次思路，顺利解决此问题，具体解决方案正如CiyLeI所说。
