### ISSUE TITLE
提交重判之后AC率那里数据会被增加

### ISSUE THREAD

**Issue by imcaffrey** [QingdaoU/OnlineJudge#39]
就是一个题原本只有一个提交，重判了几次之后，AC率变成了1/7

**Comment by imcaffrey** [comment]
以及统计的“通过的题目数”实际上是在统计通过的提交个数……

**Comment by virusdefender** [comment]
第一个，你的意思是说重判不应该增加提交次数么？

第二个，不清楚你说的什么意思。

**Comment by virusdefender** [comment]
第一个，重判和正常提交没有区别的。

第二个，试了下，正常情况下不会的。只有在第一次ac，然后wa了，再次ac同一道题才会增加提交通过的题目数量。这个受限于设计，暂时没办法。

还有问题请继续评论。

**Comment by imcaffrey** [comment]
重判不应该是指更新原来那个提交的状态吗……怎么能算作新的提交呢？

**Comment by virusdefender** [comment]
重判是更新了原来的提交，但是判题服务器返回web服务器的时候，没有任何区别，都是更新已有的submission的信息（如果非重判，时间内存就是null，否则是上次判题的数值）。

**Comment by imcaffrey** [comment]
Thx!
