### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by adamwen829** [QingdaoU/OnlineJudge#4]
https://github.com/adamwen829/OnlineJudge/blob/master/oj/settings.py#L32
SECREY_KEY 默认空来让用户自行生成，否则在 Django 1.6 以下版本存在安全风险

**Comment by imcaffrey** [comment]
:+1:

**Comment by virusdefender** [comment]
经过讨论，目前在 django 版本高于1.6的情况下，暂时没有已知的问题。接下来考虑使用更加合适的配置文件的写法。

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/blob/master/oj/custom_settings.example.py 

已经修改为这种形式了~
