### ISSUE TITLE
invalid literal for int() with base 10: '1.000'

### ISSUE THREAD

**Issue by itmir913** [QingdaoU/OnlineJudge#404]
Hello.
I tried to import problems fps data.

But, Some Error occurs. this error is : invalid literal for int() with base 10: '1.000'

In fps.xml, <time_limit unit="s">&lt;![CDATA[1.000]]&gt;</time_limit>
This part is the cause of the error.

I editted '1.000' to '1', and Success.

However, Shouldn't this error be resolved for someone else?

Thanks!

Attach log and example files : [issues.zip](https://github.com/QingdaoU/OnlineJudge/files/8159787/issues.zip)

**Comment by zhblue** [comment]
这是因为你从新版hustoj导出的文件带有小数，我把hustoj那边打了个补丁，你可以升级一下，这样如果导出的时候发现是整数秒，就不按小数形式导出，可以兼容老版本。

**Comment by zhblue** [comment]
I patched hustoj for backwards compatibility, update it and export again ,it will use integer as long as it is possible.
