### ISSUE TITLE
如何上传题目

### ISSUE THREAD

**Issue by KevinTsaiCodes** [QingdaoU/OnlineJudge#431]
如标题

TestCase 上传的档案 要上传什么档案类型，才能够成功新增题目呢

档名与副档名是什么

**Comment by KevinTsaiCodes** [comment]
我上传
input.in 和 output.in 他都说我上传不对
现在上传压缩档也说 Empty File
请问我要上传甚么才能自制题目呢

![image](https://user-images.githubusercontent.com/53148219/199840073-abcbeb54-dc61-49ea-b925-923beda48e74.png)

**Comment by KevinTsaiCodes** [comment]
![image](https://user-images.githubusercontent.com/53148219/199841443-f212104e-dc90-4c45-90f3-5599f96a6376.png)

**Comment by Jerry080801** [comment]
请问管理员是怎么加的呀

**Comment by virusdefender** [comment]
https://opensource.qduoj.com/#/onlinejudge/guide/test_case
