### ISSUE TITLE
项目还在维护吗？

### ISSUE THREAD

**Issue by mooncool** [QingdaoU/OnlineJudge#446]
如题

**Comment by virusdefender** [comment]
求接班人

**Comment by sahuang** [comment]
> 求接班人

请问现在项目的安全性还是能保障的对吗? 我们的 CTF比赛 (SekaiCTF) 已经连续两年用这个OJ了，不过自己搭了 frontend，目前看起来还好 唯一就是 docker image 的 python3/cpp 版本太低了..之后可能需要升级一下。

**Comment by mikucat0309** [comment]
沒想到這東西還這麼多人用，去年有稍微翻新一下這東西，供參

## 評測服務

當初想用 GCC 12 和 Python 3.11 才用 Debian Testing (bookworm) 當 base image，各位依需求自行更改吧

https://github.com/mikucat0309/JudgeServer

## 評測沙箱

https://github.com/mikucat0309/Judger

## 網頁後端

這裡面有兩個串接我以前學校 OAuth 的 commit，記得 cherry pick 掉
