### ISSUE TITLE
problems/?tag=a+b

### ISSUE THREAD

**Issue by imcaffrey** [QingdaoU/OnlineJudge#45]
题目标签中不允许有奇怪的符号……？能不能写在前端提醒一下……

**Comment by virusdefender** [comment]
可能是加号的escape问题，等下我看看。

什么浏览器啊

**Comment by virusdefender** [comment]
确认是`+`的问题，URL中出现`+`等符号需要进行encode操作。之前引入过，用js在前端encode，但是后来发现有XSS的问题就去掉了。

目前所有的URL都可能有这问题。暂时没想到好的办法，先避免`+ #`等特殊符号吧。
