### ISSUE TITLE
在docker 部署正确的情况下出现depend on 依赖问题 

### ISSUE THREAD

**Issue by WUYINAN-666** [QingdaoU/OnlineJudge#452]
docker-compose up -d一经执行立刻报错。尝试其他qduoj变体，如gznbuoj，可以正常部署执行。
Ubuntu和centos均有同样的问题，均全新安装，均验证docker正常安装。
![屏幕截图 2024-02-07 233046](https://github.com/QingdaoU/OnlineJudge/assets/110458588/2f37f4d7-84f4-4312-9ae4-05d7401843d5)

**Comment by HenryHe613** [comment]
检查一下docker-compose.yml，里面的judge-server改成oj-judge，但是依然无法部署

**Comment by HenryHe613** [comment]
![image](https://github.com/QingdaoU/OnlineJudge/assets/59521292/ab573d48-bf07-47c3-a5cb-5d6152a33b2d)
现在这样了，兄弟有办法解决吗？

**Comment by HenryHe613** [comment]
有一个临时的解决办法，就是版本退回到上一个去
就是这个66ddc588204a8aabfcf6a5b64573a8fecb3b8b0d
docker-compose.yml没有更新，可以正常部署

我想知道这个yaml怎么回事

**Comment by mikucat0309** [comment]
@HenryHe613 @WUYINAN-666 v1.6.0 原本想用 GHCR，但聯絡不到 org admin 更改容器權限，現在已經改用阿里雲了，再試試看。

**Comment by WUYINAN-666** [comment]
> ![image](https://private-user-images.githubusercontent.com/59521292/303217404-ab573d48-bf07-47c3-a5cb-5d6152a33b2d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4Mjc4MTQsIm5iZiI6MTcwNzgyNzUxNCwicGF0aCI6Ii81OTUyMTI5Mi8zMDMyMTc0MDQtYWI1NzNkNDgtYmYwNy00N2MzLWE1Y2ItNWQ2MTUyYTMzYjJkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjMxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzM0ZDgxNzliMWI2OGY4NzY3Yzk2NzI2YmQyOWJlNjQyNmVjOTNkYzE1OGZlYzM0NzgzYjlhNjExZTQwYTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IC4akhCn_N7womBuY0JStWqz0zD_enjz8nTpAtT9Oes) 现在这样了，兄弟有办法解决吗？

Linux 小白，建议重装😂

**Comment by WUYINAN-666** [comment]
> @HenryHe613 @WUYINAN-666 v1.6.0 原本用 GHCR，但聯絡不到 org admin 把容器設成公開，[f98842c](https://github.com/QingdaoU/OnlineJudgeDeploy/commit/f98842c67ec25d30641de767a895f2aafeca6e96) 已經改用阿里雲，Deploy 專案也明確標上 v1.6.0 的 tag，再幫我試試看。

docker换源？我试试 
谢谢你的建议
