### ISSUE TITLE
题面能否支持LaTeX

### ISSUE THREAD

**Issue by wchengk09** [QingdaoU/OnlineJudge#454]
出题的时候，只支持MarkDown，不支持LaTeX，但是LaTeX在出题的时候真的特别有用

**Comment by zhblue** [comment]
1、可以用支持的软件写好题面，截图上传
2、可以尝试二次开发，引入mathjax

**Comment by virusdefender** [comment]
https://opensource.qduoj.com/#/onlinejudge/guide/mathjax

只要公式的话，看上面的文档就行了，全文 latex 不打算支持。
