### ISSUE TITLE
docker-compose up -d失败

### ISSUE THREAD

**Issue by BugTD** [QingdaoU/OnlineJudge#457]
**全部依赖已经安装,已换源**
在docker-compose up -d时失败，具体表现为长期卡住，最终报错为：
`
ERROR: error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/e0/e012ba9b5eff3555a6504faecd45ce5919689176be8d3db8aef3857865be7a8e/data?verify=1712146873-Vxz0vX9xKRzBATTK8GsdoQFjPz4%3D": net/http: TLS handshake timeout
`
系统是debian11`Linux orangepizero3 6.1.31-sun50iw9 #1.0.2 SMP Thu Sep 28 09:07:29 CST 2023 aarch64 GNU/Linux
`

**Comment by mikucat0309** [comment]
这边没办法复现，应该是网络问题
v1.6.0 后的镜像只在阿里云有，看错误信息似乎是连到 Docker Hub 了？

**Comment by BugTD** [comment]
请问如何手动拉取`redis:4.0-alpine`和`postgres:10-alpine`呢？
可能有帮助的信息：
`root:~/OJ/OnlineJudgeDeploy# docker-compose up
Pulling oj-postgres (postgres:10-alpine)...
10-alpine: Pulling from library/postgres
6875df1f5354: Downloading [>                                                  ]  27.96kB/2.708MBlling fs layer
122972bf4697: Pulling fs layer
9e48c6fc88d9: Waiting
df256d318da7: Waiting
33b9b3130508: Waiting
62dd076388f2: Waiting
bb4469219c97: Waiting
3e9cb1d4b627: Waiting
ERROR: error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/e0/e012ba9b5eff3555a6504faecd45ce5919689176be8d3db8aef3857865be7a8e/data?verify=1712286159-etLCK1mhaeSc92xcwps50Fx6BMw%3D": net/http: TLS handshake timeout
`

**Comment by BugTD** [comment]
> 另：QQ群加不进去了

**Comment by BugTD** [comment]
> 这边没办法复现，应该是网络问题 v1.6.0 后 backend 和 judge server 的镜像只在阿里云有，看错误信息似乎是连到 Docker Hub 出错，那应该是 Redis 或 Postgres 拉失败，手动拉 `redis:4.0-alpine` 和 `postgres:10-alpine` 呢？

```
root@orangepizero3:~/OJ/OnlineJudgeDeploy# docker pull redis:4.0-alpine
4.0-alpine: Pulling from library/redis
Digest: sha256:aaf7c123077a5e45ab2328b5ef7e201b5720616efac498d55e65a7afbb96ae20
Status: Image is up to date for redis:4.0-alpine
docker.io/library/redis:4.0-alpine
root@orangepizero3:~/OJ/OnlineJudgeDeploy# docker pull postgres:10-alpine
10-alpine: Pulling from library/postgres
6875df1f5354: Downloading  54.67kB/2.708MB
0d7fcb69f233: Download complete
122972bf4697: Download complete
9e48c6fc88d9: Waiting
df256d318da7: Waiting
33b9b3130508: Waiting
62dd076388f2: Waiting
bb4469219c97: Waiting
3e9cb1d4b627: Waiting
error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/e0/e012ba9b5eff3555a6504faecd45ce5919689176be8d3db8aef3857865be7a8e/data?verify=1712286675-y%2FlXNJcXO2qk7%2BRhaMwtm1gut64%3D": net/http: TLS handshake timeout

```
在拉取`postgres:10-alpine`时，还是出现了上述问题

**Comment by mikucat0309** [comment]
> 另：QQ群加不进去了
啊這...我是真不知道情況，沒在用 QQ

> 在拉取 `postgres:10-alpine` 时，还是出现了上述问题

仔細想了下，有換鏡像源就不會連 Docker Hub，你這是沒換到吧

**Comment by BugTD** [comment]
那麼怎麼換呢😘

**Comment by mikucat0309** [comment]
> 那麼怎麼換呢😘

牆內應該可以參考這篇設定，但我沒實際試過
https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6

**Comment by BugTD** [comment]
好像可以，但是很慢

**Comment by BugTD** [comment]
![Uploading CopyQ.rxCHEw.png…]()

**Comment by BugTD** [comment]
![Uploading CopyQ.rxCHEw.png…]()

**Comment by BugTD** [comment]
现在好是好了，但是docker-compose up -d无反应

**Comment by mikucat0309** [comment]
沒有跟 OnlineJudge 相關的問題的話，這個 issue 我先關掉囉

**Comment by BugTD** [comment]
ok
