### ISSUE TITLE
gcc、g++、python添加多版本编译器问题

### ISSUE THREAD

**Issue by LYH-8112** [QingdaoU/OnlineJudge#459]
在JudgerServer中的dockerfile中，添加gcc、g++、python多版本支持时，出现如下错误，请问怎么处理？
**39.81 E: Unable to locate package \
39.81 E: Unable to locate package gcc-9
39.81 E: Unable to locate package gcc-10**

**python2提示不支持**

![QQ截图20240410104006](https://github.com/QingdaoU/OnlineJudge/assets/131565927/0acde159-be82-4332-b2b7-9164deaa34b8)

**Comment by mikucat0309** [comment]
因为 JudgeServer 环境是基于 Debian 套件，而基底镜像的 Debian 版本是 13 (trixie, testing)，`gcc-9` 和 `gcc-10` 只在 Debian 11 (bullseye, oldstable) 有，Python 2.7 只在 Debian 10 (buster) 或更早的版本才有，需要的话可以自行编译移植需要的版本到 Debian 上
题外话，GCC 是向下兼容的，需要以旧版 C/C++ 标准编译可以调整 `-std` 参数，没必要特别用旧版吧

**Comment by LYH-8112** [comment]
非常感谢。如何将Python2.7移植到Debian 13 (trixie, testing)呢？

**Comment by mikucat0309** [comment]
我不知道，也不建议这样做。
Python 2.7 已经于 2020 年停止所有维护与更新，意味着有任何漏洞也不会修复。
如果真的需要支持 Python 2.7，可以继续使用 OnlineJudge v1.5.0。
