### ISSUE TITLE
进群

### ISSUE THREAD

**Issue by t1yifang** [QingdaoU/OnlineJudge#460]
有没有人知道加群的答案 课设需要 求求求了 让我进去吧

**Comment by virusdefender** [comment]
有问题直接在这里问

**Comment by t1yifang** [comment]
不好意思 纯小白 问题有点多 可以让我进群吗 想看看大家开发的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月14日(星期天) 晚上9:39
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QingdaoU/OnlineJudge] 进群 (Issue #460)














 
有问题直接在这里问
