### ISSUE TITLE
严格按照要求仍然上传测试用例失败

### ISSUE THREAD

**Issue by garry-jay** [QingdaoU/OnlineJudge#470]
![1721725063132](https://github.com/user-attachments/assets/6c3a0487-af93-4bac-b83a-06212d99d84e)
![1721725122034](https://github.com/user-attachments/assets/607174dd-c557-4d8f-9434-a4e5fc770e82)

**Comment by mikucat0309** [comment]
請用 ZIP 格式

**Comment by garry-jay** [comment]
换成了ZIP还是不行
![24b4fb81ef70b84f41556172fdad278](https://github.com/user-attachments/assets/a9a1c354-7bd0-47bf-baab-b61d9927e3c7)

**Comment by mikucat0309** [comment]
那方便给我测资的压缩档测试吗？:sweat_smile:

**Comment by garry-jay** [comment]
[1.zip](https://github.com/user-attachments/files/16398327/1.zip)

**Comment by mikucat0309** [comment]
老兄你这还是 RAR 阿，要改用 ZIP 格式压缩，改档名没用的
![image](https://github.com/user-attachments/assets/10e47e7d-4152-4b39-ae63-5be67e1ad368)

**Comment by garry-jay** [comment]
已解决,thanks

**Comment by tangtianyi19980709** [comment]
遇到了类似的问题 上传报错empty file
