### ISSUE TITLE
使用docker-compose up -d时报错Pulling oj-judge (registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1)... ERROR: manifest for registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1 not found

### ISSUE THREAD

**Issue by leeway-z** [QingdaoU/OnlineJudge#474]
Pulling oj-judge (registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1)...
ERROR: manifest for registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1 not found

**Comment by mikucat0309** [comment]
請問您用的 CPU 架構是什麼呢？我剛確認 linux/amd64 和 linux/arm64 是沒問題的

**Comment by leeway-z** [comment]
谢谢您的回复，我使用的是linux系统，虽然不知道这个问题产生的原因是什么。我个人认为应该是网络问题，我把docker架构重装完就成功了。




进来看看
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QingdaoU/OnlineJudge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QingdaoU/OnlineJudge] 使用docker-compose up -d时报错Pulling oj-judge (registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1)... ERROR: manifest for registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1 not found (Issue #474)





 
請問您用的 CPU 架構是什麼呢？我剛確認 linux/amd64 和 linux/arm64 是沒問題的

**Comment by leeway-z** [comment]
目前又出现了一个在提交代码时系统错误的问题，导致所有代码无法提交


进来看看
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leeway"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 下午4:45
***@***.***&gt;;

主题:&nbsp;回复： [QingdaoU/OnlineJudge] 使用docker-compose up -d时报错Pulling oj-judge (registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1)... ERROR: manifest for registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1 not found (Issue #474)



谢谢您的回复，我使用的是linux系统，虽然不知道这个问题产生的原因是什么。我个人认为应该是网络问题，我把docker架构重装完就成功了。




进来看看
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "QingdaoU/OnlineJudge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QingdaoU/OnlineJudge] 使用docker-compose up -d时报错Pulling oj-judge (registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1)... ERROR: manifest for registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1 not found (Issue #474)





 
請問您用的 CPU 架構是什麼呢？我剛確認 linux/amd64 和 linux/arm64 是沒問題的

**Comment by ciao1** [comment]
请问系统错误system error的错误解决了吗？
