### ISSUE TITLE
A+B问题，提交Java代码Compile Error，C/C++语言OK

### ISSUE THREAD

**Issue by huzuli** [QingdaoU/OnlineJudge#48]
提交Java代码到判提服务器上报错：
*** Error in `/usr/bin/javac': double free or corruption (fasttop): 0x00007ff51400c300 ***
*** Error in `/usr/bin/javac': double free or corruption (fasttop): 0x00007ff514014850 ***
*** Error in `/usr/bin/javac': double free or corruption (fasttop): 0x00007ff51400bec0 ***
*** Error in `/usr/bin/javac': double free or corruption (fasttop): 0x00007ff51400bc20 ***
*** Error in `/usr/bin/javac': double free or corruption (out): 0x00007ff51401c070 ***
*** Error in `/usr/bin/javac': double free or corruption (out): 0x00007ff51401c070 ***
*** Error in `/usr/bin/javac': double free or corruption (out): 0x00007ff51401c070 ***
*** Error in `/usr/bin/javac': double free or corruption (!prev): 0x00007ff51401c070 ***
*** Error in `/usr/bin/javac': double free or corruption (!prev): 0x00007ff51401c070 ***
*** Error in `/usr/bin/javac': double free or corruption (!prev): 0x00007ff51401c070 ***

Java源码：
import java.util.Scanner;
public class Main{
    public static void main(String[] args){
        Scanner in=new Scanner(System.in);
        int a=in.nextInt();
        int b=in.nextInt();
        System.out.println((a+b));  
    }
}

在判题服务上直接执行时OK的：
/usr/bin/javac Main.java -d ./ -J-Xss1m -J-XX:MaxPermSize=16M -J-XX:PermSize=8M -J-Xms16m -J-Xmx1024m -encoding UTF8

/usr/bin/java -cp ./ -Xss1M -XX:MaxPermSize=16M -XX:PermSize=8M -Xms16M -Xmx128M -Djava.security.manager -Djava.security.policy==policy -Djava.awt.headless=true Main

看过之前的一个说Java内存要增大的issue，可是我把 Xmx 增大到500M也不好用。

C和C++ 代码是没问题的。

**Comment by virusdefender** [comment]
奇怪，像是javac的问题，但是这么简单的代码不应该触发bug啊。

你先尝试重启一下judger容器。

在judger目录中运行`docker-compose restart`。

**Comment by virusdefender** [comment]
经过讨论，可能又是Java内存分配的一个坑。

楼主的内存服务器256G内存。Xmx等参数没能限制Java分配过多的内存，将judger的内存限制提高为2G就可以了。
