### ISSUE TITLE
根据现有的文档，celery命令出错

### ISSUE THREAD

**Issue by bhzhu203** [QingdaoU/OnlineJudge#5]
ImportError: No module named judger_controller

现在是不是改成了  celery -A judge.server worker -l DEBUG 

如果是，也占用了127.0.0.1:8080端口

请更新一下文档，判题服务器的配置细节，谢谢啦

**Comment by imcaffrey** [comment]
:+1:

**Comment by virusdefender** [comment]
抱歉，现在的文档是老版本的，新的还没有写。

这几天我有空改下吧。

**Comment by virusdefender** [comment]
立 flag，下周一之前一定写完。

**Comment by virusdefender** [comment]
http://qingdaou.github.io/OnlineJudge/

文档已经更新，但是还有些简陋。

我找了几个完全没接触过的小伙伴按照文档安装测试，有问题会随时改的。
