### ISSUE TITLE
2.0重构版规划

### ISSUE THREAD

**Issue by virusdefender** [QingdaoU/OnlineJudge#50]
本OJ大约是1年前开始开发的，目前逐渐暴露出一些问题。打算进行一个比较大的重构，主要包括
- [x]  vue.js重写所有前端页面
- [x]  前端后端的国际化，多语言和时区
- [x]  导入导出题目（但是目前考虑的hustoj的FPS格式还有些问题，可能在当前版本中也会做）
- [x]  更方便的添加多编程程序语言支持，统一配置规则（有些问题还没解决）题目选择可以使用的语言
- [x]  比赛的OI模式（排名，查看单独测试数据是否通过等）
- [x] SPJ更加方便的添加代码和测试
- [x]  超级管理员 - 管理所有 普通管理员- 默认创建小组内比赛和不能创建题目题目，但是可以通过两个选项允许
- [x]  完善后端的测试，跑CI
- [x]  代码风格问题
- [x]  题目和公告使用markdown编辑器
- [x] 判题服务器的健康检查和添加时候的检查

目前基本上只有我一个人在维护这个项目，时间不多，都是在工作之余做，但是放弃了也太可惜。如果有愿意参与的，可以回复一下。

扫描二维码献出你的一份爱心

![wxpay](https://user-images.githubusercontent.com/4939404/35159696-02000c44-fd76-11e7-94d4-f00773ac1901.jpg)

**Comment by igoing** [comment]
Python菜鸟问一句，有什么要求吗？

**Comment by virusdefender** [comment]
@igoing 能熟练规范的写django，前端也行

**Comment by imcaffrey** [comment]
@Too-Naive

**Comment by Too-Naive** [comment]
…我怎么躺着中枪阿

**Comment by Sengxian** [comment]
支持！

**Comment by Neroldy** [comment]
支持，这个OJ说实话写的很漂亮。楼主辛苦了。

**Comment by 1335661317** [comment]
支持啦~

**Comment by l861898907** [comment]
很想帮的什么……然而只是个菜鸟的OIer

**Comment by virusdefender** [comment]
再刷一遍，大家见谅。

目前基本上只有我一个人在维护这个项目，时间不多，都是在工作之余做，希望有一个伙伴可以一起维护这个项目。大家有合适的也可以推荐一下。

最看重的不是写的快慢，而是质量。

**Comment by Bokjan** [comment]
精神支持扬哥！（因为不会Py

**Comment by PENGZhaoqing** [comment]
支持，可惜只是比较熟悉Rails框架和Ruby，Django和python语言基本才起步。。等手头的活忙完了就过来看看。。

**Comment by tnoysky** [comment]
只会HTML的弱菜路过……

**Comment by tridays** [comment]
支持，楼主辛苦，可惜熟悉的后端不是 Python 没法尽绵薄之力……

**Comment by Ruanxingzhi** [comment]
支持，楼主辛苦，可惜熟悉的后端不是 Python 没法尽绵薄之力……

**Comment by zxysilent** [comment]
加油

**Comment by Kingwl** [comment]
大佬来带我啊233

**Comment by virusdefender** [comment]
@Kingwl 来来来。。

**Comment by psychicalcoder** [comment]
我也想學習寫個OJ
樓主加油！

**Comment by YOUSIKI** [comment]
为什么不开放每个题的运行效率榜呢？

**Comment by zema1** [comment]
@YOUSIKI 这个或许可以有，说不定2.0版就有了哈哈

**Comment by ILoveChenKX** [comment]
嗯，支持支持

**Comment by fsxchen** [comment]
楼主你好，会python，了解django，现在还能参加这个项目否。邮箱 fsxchen@163.com

**Comment by MascoSkray** [comment]
千呼万唤始出来，今日一看吓一跳

**Comment by QWganker** [comment]
good

**Comment by Kingwl** [comment]
it's very helpful to me!

**Comment by hirCodd** [comment]
对我很有帮助，二次开发的路上，虽然有很多困难，但是在努力克服中...

**Comment by QWganker** [comment]
建议升级到2.0
