### ISSUE TITLE
删除一些用户和提交

### ISSUE THREAD

**Issue by PENGZhaoqing** [QingdaoU/OnlineJudge#52]
因为当前版本的OJ没有删除功能，想要删除一些用户和提交。。。

**Comment by PENGZhaoqing** [comment]
若不在意数据的话，可以直接删除Mysql的文件数据（/home/data/mysql）

**Comment by PENGZhaoqing** [comment]
不要直接用一些指令来reset migration，可能各个app之间数据有联系，要删除就要全部删除。而用指令python manage.py flush等，会导致一些问题

**Comment by virusdefender** [comment]
不好意思，白天出去了。

数据库中的任何数据都是不建议删除的，OJ里面都是使用了一个`status`字段做伪删除。

题目比赛等都可以使用隐藏功能代替删除。

**Comment by PENGZhaoqing** [comment]
这个判题服务器与Web语言有关么？
若后期老板要求多了，只能自己弄个Ruby版的。。。
-感谢 @virusdefender

**Comment by virusdefender** [comment]
@PENGZhaoqing 

增加新语言没啥难度，只是暂时开发其他语言的sandbox有点困难。

Python的在一个单独分支上，见 https://github.com/QingdaoU/OnlineJudge/tree/python-support  没有sandbox。你可以参考下。

OnlineJudge 2.0规划中有多语言评测的支持，但是目前还遥遥无期。。。太忙了 

😔 😔 😔
