### ISSUE TITLE
能否提供Markdown支持

### ISSUE THREAD

**Issue by Ruanxingzhi** [QingdaoU/OnlineJudge#53]
如题。
QDUOJ并不支持以**Markdown**描述题面，但是我们很喜欢Markdown……

大概需要的地方：题目描述、公告栏.

**Comment by virusdefender** [comment]
感谢。我查一下实现方法。

**Comment by Bokjan** [comment]
曾经用过showdown.js，应该是改起来成本最小的方法之一。

**Comment by virusdefender** [comment]
主要是需要后台编辑器的支持

**Comment by virusdefender** [comment]
![image](https://cloud.githubusercontent.com/assets/4939404/17276477/6e809f7a-575d-11e6-90b3-df3a4e119afc.png)

在新版的admin上加上了，旧版本的暂时不会改了，因为使用了webpack，所以没办法移植到现在的版本上了。期待新版本吧。
