### ISSUE TITLE
关于开栈

### ISSUE THREAD

**Issue by Ruanxingzhi** [QingdaoU/OnlineJudge#55]
在数据结构题中经常出现大规模的DFS，这时有可能被**栈空间**卡掉（爆栈，返回“段错误”）。
请问如何给程序233MB的栈空间？

Ubuntu Linux 14.04 x64。
![爆栈](http://i1.piimg.com/567571/49c2fba40660e26b.png)

**Comment by virusdefender** [comment]
估计得自己改一下  https://github.com/QingdaoU/Judger/blob/master/runner.c#L24  然后重启Judger容器

编译参数不太清楚需不需要改

**Comment by Ruanxingzhi** [comment]
![233](http://ruanx.pw/img/汗.png) 然而我找不到那个 `runner.c` 啊……

**Comment by virusdefender** [comment]
在/tmp/judger下有，然后重新编译。

**Comment by Ruanxingzhi** [comment]
如何重新编译？

**Comment by virusdefender** [comment]
`sudo python setup.py install`

**Comment by Ruanxingzhi** [comment]
*Bug*
栈的大小设置成`256 * 1024 * 1024`之后，仍然爆栈。
但是在本地测试，233MB的栈就能通过。

[Example](http://fzoj.ml/submission/6deb3b8631694c0d02d76e7ec5b4ffe6/)

**Comment by virusdefender** [comment]
感觉和编译参数也有关吧，代码开头加上

```
#pragma comment(linker, "/STACK:268435456")
```

试试

**Comment by Ruanxingzhi** [comment]
然而仍然无效……

`runner.c`:
```c
#pragma comment(linker, "/STACK:233333333")

//Something...
#include "logger.h"

#define STACK_SIZE (233333333)
```

`提交的程序`:
```cpp
#pragma comment(linker, "/STACK:233333333")

//Do sth.
```

**Comment by virusdefender** [comment]
不知道了。。。但是总感觉栈本来就不应该开这么大。。。。。。。

**Comment by imcaffrey** [comment]
所以最后是怎么解决的。。。。
像lemon那样自定义编译参数吗？

**Comment by Ruanxingzhi** [comment]
@imcaffrey 最后没解决，`-Wl,stack=xxxx`对Linux没用

**Comment by imcaffrey** [comment]
@Ruanxingzhi ulimit？

**Comment by Ruanxingzhi** [comment]
@imcaffrey 尝试过
