### ISSUE TITLE
提交页面总是500错误

### ISSUE THREAD

**Issue by Morningtea7** [QingdaoU/OnlineJudge#57]
判题服务器与web服务器在同一服务器上，提交评测正常，点击“查看详情”可以正常显示判题结果。但是直接访问/submissions/就会报500.

**Comment by virusdefender** [comment]
麻烦贴一下django.log里面的报错信息

**Comment by Morningtea7** [comment]
`[ERROR]- Internal Server Error: /submissions/
Traceback 

(most recent call last):
  File "/usr/local/lib/python2.7/site-

packages/django/core/handlers/base.py", line 149, in get_response
    response = 

self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-

packages/django/core/handlers/base.py", line 147, in get_response
    response = 

wrapped_callback(request, *callback_args, **callback_kwargs)
  File 

"/code/account/decorators.py", line 31, in __call__
    return self.func(*args, **kwargs)
  

File "/code/submission/views.py", line 326, in submission_list_page
    "show_all": 

show_all})
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in 

render
    template_name, context, request=request, using=using)
  File 

"/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in 

render_to_string
    return template.render(context, request)
  File 

"/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in 

render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/base.py", line 206, in render
    return self._render(context)
  

File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
 

   return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/base.py", line 992, in render
    bit = node.render_annotated

(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 959, 

in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/loader_tags.py", line 173, in render
    return 

compiled_parent._render(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/base.py", line 197, in _render
    return self.nodelist.render

(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 992, 

in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/base.py", line 959, in render_annotated
    return self.render

(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", 

line 69, in render
    result = block.nodelist.render(context)
  File 

"/usr/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    

bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/base.py", line 959, in render_annotated
    return self.render

(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", 

line 220, in render
    nodelist.append(node.render_annotated(context))
  File 

"/usr/local/lib/python2.7/site-packages/django/template/base.py", line 959, in 

render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/base.py", line 1043, in render
    output = 

self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.7/site-

packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  

File "/code/utils/templatetags/submission.py", line 29, in translate_language
    return {1: 

"C", 2: "C++", 3: "Java"}[value]
KeyError: 4L
2016-08-16 08:51:07,668 

[MainThread:140592958949120] [django.request:182] [base:get_response]`

**Comment by Ruanxingzhi** [comment]
您的操作系统是什么啊……

**Comment by virusdefender** [comment]
不好意思，现在才过来看。

您使用的是master分支上的代码么？正常情况下，没有language code 为 4的情况啊。

**Comment by hustanhuang** [comment]
是不是用的python-support分支的代码。。那个分支里面给python分的language code是4

**Comment by Morningtea7** [comment]
我是按照wiki里面正式部署文档安装的

**Comment by Morningtea7** [comment]
曾尝试添加pascal语言，分配了language code=4,但是现在已经删除相关代码，仍然报500错误

**Comment by virusdefender** [comment]
@Morningtea7 那是因为数据库中code=4还是存在的，但是实际的代码并没有考虑这个，然后就出问题了。

**Comment by virusdefender** [comment]
进入oj_web_server容器，运行`python manage.py shell`

执行下面的命令删除code=4的提交

```
>>> from submission.models import Submission
>>> print Submission.objects.filter(language=4).count()
>>> Submission.objects.filter(language=4).delete()
```

**Comment by Morningtea7** [comment]
@virusdefender 问题已解决
