### ISSUE TITLE
问题页面问题描述不换行

### ISSUE THREAD

**Issue by BillAlen** [QingdaoU/OnlineJudge#58]
HTML的换行要用`<br/>`的，加个转换把`\n`替换成`<br/>`就行了
举个栗子[https://qduoj.com/problem/39/](https://qduoj.com/problem/39/)

**Comment by virusdefender** [comment]
https://docs.djangoproject.com/en/dev/ref/templates/builtins/#linebreaksbr

稍后看下

**Comment by virusdefender** [comment]
fixed，请按照wiki升级测试下。
