### ISSUE TITLE
正式部署的时候在运行docker-compose up -d时报错/code/dockerfiles/oj_web_server/run.sh: No such file or directory

### ISSUE THREAD

**Issue by h094071** [QingdaoU/OnlineJudge#62]
运行
docker logs ID
报错：
/code/dockerfiles/oj_web_server/run.sh: No such file or directory

**Comment by Ruanxingzhi** [comment]
您这问题没法复现啊……  
您是自行build的镜像吗？

**Comment by kh953120** [comment]
我也遇到了，我是沒有下載原始碼直接 使用 docker hub 的 image。
後來下載原始碼自己build就好了。

**Comment by virusdefender** [comment]
请看wiki的faq，这个文件是外部映射进去的，如果路径写的不对就会这样。
