### ISSUE TITLE
mysql 拒绝访问

### ISSUE THREAD

**Issue by h094071** [QingdaoU/OnlineJudge#63]
3个容器全部正常启动了，在执行`docker exec -i -t {CONTAINER ID} /bin/bash` 显示 ：

```
Failed to create database, error: (1045, "Access denied for user 'root'@'172.17.0.4' (using password: YES)"), will retry in 3 seconds
  mysql  environment:
        - MYSQL_ROOT_PASSWORD=123456
```

执行`docker exec -it f06c544381e8  /bin/bash mysql -u root -p` 同样报错：

```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
'''
单独启动mysql的镜像，并在mysql的容器中进行链接数据库：
'''
docker run --rm  --name some-mysql -e MYSQL_ROOT_PASSWORD=123456    mysql
`docker exec -it some-mysql  /bin/bash mysql -u root -p`
'''
 能连上数据库（但是如同下面，使用主机共享的文件，数据库连不上了）
```
docker run --rm  --name some-mysql -e MYSQL_ROOT_PASSWORD=123456  -v /Users/home/learn/oj/data/mysql:/var/lib/mysql  mysql
docker exec -it some-mysql  /bin/bash mysql -u root -p
```

 链接不上

应该是目录的权限问题，对docker不是很熟，望指点一下，系统是Mac系统

**Comment by Ruanxingzhi** [comment]
Maybe you can try `mysql -h 172.17.0.4 -uroot -p`

**Comment by virusdefender** [comment]
有点奇怪，你去看下MySQL容器里面的环境变量。密码是不是你设置的那个

**Comment by virusdefender** [comment]
你去MySQL容器内看下环境变量里面的密码是不是对的

**Comment by h094071** [comment]
@Ruanxingzhi @virusdefender  你们建议都尝试了一下，但问题还没有解决，我觉的还是目录的权问题，不知道怎么设置了

**Comment by h094071** [comment]
清楚主机下的mysql中的文件后，问题解决了，谢谢大家
