### ISSUE TITLE
提交问题时出现无法获取title

### ISSUE THREAD

**Issue by bestony** [QingdaoU/OnlineJudge#64]
- 在后台创建问题时，报错title没有填写
  - 错误提示：title : This field may not be blank.
  - 没找到VM怎么定义的。
  - chrome 版本 54.0.2840.99 m (64-bit)
![-1611302140](https://cloud.githubusercontent.com/assets/13283837/20736005/c1471816-b6de-11e6-9aef-5eaa4ea89b18.png)

**Comment by virusdefender** [comment]
谢谢~

感觉是一个不好复现的问题，有空看下~

**Comment by bestony** [comment]
我也是偶尔才会遇到，添加内容有些时候会报错。vm是如何定义的？我想自己调试一下。完全从头开始看担心有点慢。。。

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/blob/master/static/src/js/app/admin/problem/addProblem.js#L113

现在用的框架比较蛋疼

**Comment by drops123456** [comment]
![image](https://cloud.githubusercontent.com/assets/20397875/20789669/418975ca-b7f0-11e6-82b3-129795cd09e6.png)
这个复制一份是复制到哪，两个目录都要有嘛
