### ISSUE TITLE
nginx服务起不来

### ISSUE THREAD

**Issue by drops123456** [QingdaoU/OnlineJudge#65]
![image](https://cloud.githubusercontent.com/assets/20397875/20789762/a8d730e6-b7f0-11e6-91f5-06a92bd17373.png)
参照w网上的重启，还有sudo 都无法解决。

**Comment by virusdefender** [comment]
请检查一下是不是`oj.conf`变成了一个文件夹，如果是，请删除，然后检查`oj.conf.example`是否复制为了`oj.conf`，还有`oj.conf`的路径是否正确。

**Comment by virusdefender** [comment]
涉及到`**.example.**`的时候都要当前目录复制一份，去掉`.example`
