### ISSUE TITLE
requirements.txt 问题

### ISSUE THREAD

**Issue by mapleray** [QingdaoU/OnlineJudge#7]
建议 `requirements.txt` 使用 `pip freeze` 对于各种库加上版本信息，在项目根目录放 `requirements.txt` 可能会更好点

**Comment by virusdefender** [comment]
谢谢。

这个文件和其他的配置文件都在在 dockerfiles 文件夹中，build 镜像的时候会用到，所以就没有单独拿出来。

目前测试所有的库使用最新的都没有问题，就先不 freeze 了。

**Comment by mapleray** [comment]
看见在 dockerfiles 里了，但是没加版本号，貌似项目用的是1.8的 django 吧，现在镜像库里面已经有1.9的了，1.9已经提示几个用法已经废弃了

**Comment by virusdefender** [comment]
谢谢。

现在有一个 warning，但是这个只是因为与一个废弃的设置同名导致的。

这个工程创建的时候使用的是1.7或者是1.8，现在运行没有问题。

使用新版本的库没什么坏处的，我们会持续维护的。
