### ISSUE TITLE
master djangorestframework版本固定

### ISSUE THREAD

**Issue by xudianc** [QingdaoU/OnlineJudge#72]
`djangorestframework`最新版3.6.2需要在`ModelSerializer`类中指定参数 fields，否则报错:

> 
The ModelSerializer and HyperlinkedModelSerializer classes should now include either a fields or exclude option, although the fields = '__all__' shortcut may be used. Failing to include either of these two options is currently pending deprecation, and will be removed entirely in the 3.5 release. This behavior brings ModelSerializer more closely in line with Django's ModelForm behavior.

解决方案: `/dockerfiles/oj_web_server/requirements.txt中djangorestframework` 指定版本3.4.0

**Comment by virusdefender** [comment]
不好意思，拖了很久，最新 master 中已经 freeze 版本。
