### ISSUE TITLE
扩大栈空间

### ISSUE THREAD

**Issue by sylxjtu** [QingdaoU/OnlineJudge#73]
希望提供选项在判题时中扩大栈空间到内存限制，防止出现爆栈。

**Comment by hustanhuang** [comment]
#55 提过这个问题。

**Comment by Ruanxingzhi** [comment]
然而 #55  并没有得到解决。

**Comment by virusdefender** [comment]
这个问题在最新版的 Judger 中提供了配置选项，这个空间还是受限于 rlimit。

https://github.com/QingdaoU/Judger/commit/099ec07db784ad0635d8e1c1460a40c9dabba153
