### ISSUE TITLE
支持Python

### ISSUE THREAD

**Issue by davideuler** [QingdaoU/OnlineJudge#75]
希望能够支持选择python来答题

**Comment by zjuchenyuan** [comment]
请看python-support分支，使用前你需要merge到master分支上

目前python-support也仅仅支持python2，没有沙箱，不建议在生产环境使用

**Comment by davideuler** [comment]
多谢，赞

**Comment by davideuler** [comment]
试用了一下，果然可以用：

$cd /home/OnlineJudge
$git merge origin/python-support

**然后重新生成压缩的js就可以了。**
docker exec -i -t ojwebserver_oj_web_server_1 /bin/bash
然后再次运行 python tools/release_static.py，以生成压缩版的js，此过程较慢，请耐心等候。（必须运行）

然后 exit 退出 docker 容器，docker restart {CONTAINER ID}重启。

docker restart ojwebserver_oj_web_server_1
docker log ojwebserver_oj_web_server_1
docker restart
