### ISSUE TITLE
nginx配置問題？

### ISSUE THREAD

**Issue by tico88612** [QingdaoU/OnlineJudge#81]
<img width="1238" alt="2017-06-01 1 59 01" src="https://cloud.githubusercontent.com/assets/17496418/26646393/fadc8204-466d-11e7-8336-9aa4bf53b459.png">
我本身沒有裝nginx
logs也沒有顯示任何東西
阻擋port的程式也關閉了
我wiki也看了
我還有哪些地方沒有用到？
謝謝

**Comment by virusdefender** [comment]
`lsof -i:80` 看一下

**Comment by tico88612** [comment]
沒有顯示東西

**Comment by virusdefender** [comment]
但是就是提示80端口被占用了啊

**Comment by tico88612** [comment]
<img width="561" alt="2017-06-04 4 10 41" src="https://cloud.githubusercontent.com/assets/17496418/26759991/7ba3247c-4940-11e7-9412-2794f4780e8a.png">
應該是這個，apache2關掉了但還是無法啟動

**Comment by virusdefender** [comment]
`docker rm -f $(docker ps -aq)` 然后重新 `docker-compose` 启动试试

**Comment by tico88612** [comment]
Creating ojwebserver_nginx_1 ... 
Creating ojwebserver_nginx_1 ... error

ERROR: for ojwebserver_nginx_1  Cannot start service nginx: containerd: container not started

ERROR: for nginx  Cannot start service nginx: containerd: container not started
ERROR: Encountered errors while bringing up the project.

依舊還是一樣訊息

**Comment by virusdefender** [comment]
额，麻烦稍等下吧。我这几天有空可能会修改下部署方法，把 Nginx 放在容器里面。

**Comment by virusdefender** [comment]
你要不试试最新的 master，注意 readme 中部署文档更换了。可以设置端口映射方式。
