### ISSUE TITLE
允许使用名称作为评测机的地址

### ISSUE THREAD

**Issue by amphineko** [QingdaoU/OnlineJudge#82]
docker-compose 跨 project 的网络调试太麻烦了，就打算把 judger 和 oj_web_server 放在同一个 project 里

然后发现 JudgeServer 的 IP 真的只能填 IP (。 

希望能用名称作为评测机的地址

**Comment by amphineko** [comment]
我现在已经把 judger 和 web_server 放在同一个 compose 文件里了

但是因为评测机地址那里只能填 IP，所以还是得先用 inspect 查 judger 的 IP 地址

**Comment by virusdefender** [comment]
哈哈哈，这已经是一两年前的项目了，问题还是有一些的，但是一直没空改。

**Comment by virusdefender** [comment]
在 https://github.com/QingdaoU/OnlineJudgeDeploy 的新镜像里面已经在着手处理这些问题了，你可以参考下。

**Comment by virusdefender** [comment]
新版本在 master 发布，统一使用了 judger 的域名
