### ISSUE TITLE
登入xss攻擊

### ISSUE THREAD

**Issue by maple3142** [QingdaoU/OnlineJudge#84]
url的__from參數可以加入javascript
xxxxxxx/login/?__from=javascript:alert(document.cookie)

**Comment by virusdefender** [comment]
感谢，稍后修复~

**Comment by virusdefender** [comment]
https://github.com/QingdaoU/OnlineJudge/commit/1cfa17e48bf1b1ca66b976a00051d481abe3cb8d

能否像 virusdenfeder@outlook.com 发封邮件，想找个办法感谢一下，因为看您好像是台湾的，不太清楚你们是否使用微信或者支付宝？

**Comment by maple3142** [comment]
不用了，能夠修復就好了

**Comment by virusdefender** [comment]
谢谢~
