### ISSUE TITLE
题目列表按难度排序的一个Bug

### ISSUE THREAD

**Issue by YOUSIKI** [QingdaoU/OnlineJudge#92]
在题目页面，点一下难度可以从简单到难排序，但是如果此时点一下NextPage，不会跳转到
`https://qduoj.com/problems/2/?order_by=difficulty`
而是会跳转到
`https://qduoj.com/problems/2/`

**Comment by YOUSIKI** [comment]
另求qudoj用户群

**Comment by virusdefender** [comment]
群在 readme 中有

**Comment by zema1** [comment]
新版已不存在这个问题，欢迎使用新版OJ
