### ISSUE TITLE
刷通过题目数bug

### ISSUE THREAD

**Issue by oneofsunshine** [QingdaoU/OnlineJudge#93]
题目通过后,提交代码`1`，再提交ac代码，通过题目数会加1

**Comment by virusdefender** [comment]
这个是预期的行为，因为每个用户对于一道题目的通过情况只有一个标记位。

理论上可以通过查询历史提交来实现，但是考虑到可能的性能问题就没有做。

在新版中会考虑的，十分感谢。

**Comment by oneofsunshine** [comment]
请问怎样来更新数据库使通过题目数正常？

**Comment by virusdefender** [comment]
从 Submission 表中重新统计吧

**Comment by oneofsunshine** [comment]
需要自己写代码重新统计吗？菜菜鸟，不太懂。另外请问一下排名中显示的表是哪的数据？

**Comment by virusdefender** [comment]
如果你想修正的话，那得自己写代码统计下。

题目通过信息在个人信息中的一个 JSON 字段中。

**Comment by oneofsunshine** [comment]
好的，谢谢大佬~
