### ISSUE TITLE
judger和oj_web_server下面找不到.yml文件

### ISSUE THREAD

**Issue by MarkKobs** [QingdaoU/OnlineJudge#94]
在配置判题服务器的时候，参考正式部署方式下，
在 `dockerfiles/oj_web_server`和`dockerfiles/judger`分别有一个 `docker-compose.example.yml`。我就是没有找到这个文件`docker-compose.example.yml`。

而且我想问清楚的一点是，这个文档已经过时了对吧，那么我运行结果出现System error运行时间超时，要怎么解决呢？

**Comment by virusdefender** [comment]
是的，文档已经过时，在文档开头有说明。

最新的文档在 https://github.com/QingdaoU/OnlineJudgeDeploy

**Comment by MarkKobs** [comment]
我设置判题服务器地址为`judger`，运行结果`System Error: Invalid token`
当我设置判题服务器地址为我的服务器IP时，运行结果是`System Error`，然后会显示超时。
token已经确认正确。
