### ISSUE TITLE
2.0版本在OI模式下的BUG

### ISSUE THREAD

**Issue by zqqian** [QingdaoU/OnlineJudge#97]
AC一道题之后
再提交一遍有问题的代码
在problem列表那里的 √ 就变成了 —，变成了没有通过这道题的状态

**Comment by zema1** [comment]
OI模式的结果最后一次提交为准[http://docs.onlinejudge.me/#/onlinejudge/guide/contest_rule_type](http://docs.onlinejudge.me/#/onlinejudge/guide/contest_rule_type)

**Comment by zqqian** [comment]
但是别的OI的OJ比如LOJ都是只要AC过一道题就始终显示AC
不管最后一次提交是什么状态

**Comment by zema1** [comment]
恩 感谢你的反馈 目前打算在比赛内仍以最后一次为准，在公开题目列表下的题目AC后将保持AC状态

**Comment by zema1** [comment]
请更新至新版，如有问题再reply
