### ISSUE TITLE
希望增加的一些小细节

### ISSUE THREAD

**Issue by zqqian** [QingdaoU/OnlineJudge#99]
1
希望可以指定某些账户（比如管理员发布题目和测试题目的账户）为保留账户，不参与排行榜的显示。
因为在发布题目之后需要跑一遍标程，但是跑过之后又会在rank榜上留下太多的提交记录。
发布题目的管理员账号一直霸占着排行榜的第一位。实在不太好看。
或者提供删除提交记录这个功能也可以。

2
添加题目时候的ID那一栏现在是空白的，需要手动添加。希望可以默认显示一个新ID。

3
提交测试样例的时候只支持.out 不支持.ans
在某些网站下载下来的测试样例是.ans格式的，还需要解压下来更改后缀名后再压缩上传。
希望可以直接支持.ans文件。

4
测试样例貌似必须得从1.in 1.out开始？有时候样例是0.in 0.out就无法识别了

5 OI赛制下的每个测试点的分数默认是0
但是在一道题有十个甚至二十个测试点的时候需要手动把每个测试点的0改成10或者5。需要改十遍或者二十遍。
如果可以在上传测试数据之后，自动把score显示成 （100 / 测试点数量） 就好了，然后单独对每个测试点修改也比较方便。

6 默认内存那里一直是256MB
我所在的服务器256MB不足以启动JAVA虚拟机，所以每道题的最小内存是512MB。
但是别的出题人再添加题目的时候不知道这个问题，经常会出现没有改默认的256MB的情况，然后有人用JAV提交题目之后才发现问题。
所以能不能提供一个选项来设置默认的内存大小？或者自动保存上一次使用的内存大小？

以上是我在使用这个OJ系统时发现的一些不太好用的小细节。
因为我以前没有接触过Python, Django，所以上面说的自己在底下折腾了好长时间也没有修改成功。
所以只能提一下issue，希望引起开发者的注意。
当然如果开发者认为不需要改动的话也没关系的。

**Comment by virusdefender** [comment]
1.  按照惯例是用户名为`*`开头就不参与排名，新版本暂时没有实现，会考虑的。
2.  如果没有填写，显示的id默认会是数据库id
3.  这个 judge_server 也是支持的，但是目前后端限制的比较严格
4.  这个也是后端的限制
5.  这个可以加的
6.  Java内存的问题确实比较头疼，一直也没太好的解决，默认512也是可以的。

你提的问题都很好，十分感谢。有任何进展会在这里说明的。

@zema1

**Comment by zqqian** [comment]
如果没有填写ID的话会显示 Display ID is required 要求必须要填写

**Comment by zema1** [comment]
请运行`docker-compose pull && docker-compose up -d`更新至最新版，针对这几个问题，新版目前的解决办法为:

1. 所有admin角色的用户都将不再参与rank排名，包括用户rank和比赛rank
1. `Display ID` 现在是必须填的，题都出了，填个ID应该很轻松的 : )
1. 这个是此OJ的规范。实际上将所有`.ans`的文件改为`.out`是很简单的，比如linux下的使用这条语句:
    ```bash
    for f in *.ans; do mv $f ${f/%ans/out}; done 
    ```
1. 规范+1
1. 如你所愿
1. 实际上JVM申请的内存和你机器的大小有关，这个问题还未解决，确实比较蛋疼。但默认设置为`512MB`对其他语言来说太宽松，如果您有什么好的想法欢迎进群讨论。

感谢反馈

**Comment by zqqian** [comment]
非常感谢！
